package com.jorchi.elevator.orm.mapper;

import com.jorchi.elevator.orm.model.CheckItemInfo;
import com.jorchi.elevator.orm.model.CheckItemInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int countByExample(CheckItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int deleteByExample(CheckItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int insert(CheckItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int insertSelective(CheckItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    List<CheckItemInfo> selectByExample(CheckItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    CheckItemInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CheckItemInfo record, @Param("example") CheckItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CheckItemInfo record, @Param("example") CheckItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckItemInfo record);
}