package com.jorchi.elevator.orm.mapper;

import com.jorchi.elevator.orm.model.CheckInfo;
import com.jorchi.elevator.orm.model.CheckInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int countByExample(CheckInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int deleteByExample(CheckInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int insert(CheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int insertSelective(CheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    List<CheckInfo> selectByExample(CheckInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    CheckInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CheckInfo record, @Param("example") CheckInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CheckInfo record, @Param("example") CheckInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CheckInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CheckInfo record);
}