package com.jorchi.elevator.orm.mapper;

import com.jorchi.elevator.orm.model.Code;
import com.jorchi.elevator.orm.model.CodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    List<Code> selectByExampleWithBLOBs(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    Code selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Code record);
}