package com.jorchi.elevator.orm.mapper;

import com.jorchi.elevator.orm.model.UList;
import com.jorchi.elevator.orm.model.UListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int countByExample(UListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int deleteByExample(UListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int insert(UList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int insertSelective(UList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    List<UList> selectByExample(UListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    UList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UList record, @Param("example") UListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UList record, @Param("example") UListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UList record);
}