package com.jorchi.elevator.orm.model;

import java.util.Date;

public class CheckInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.USERID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.E_ID
     *
     * @mbggenerated
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.SCANTIME
     *
     * @mbggenerated
     */
    private Date scantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.STARTTIME
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.ENDTIME
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.UPLOADTIME
     *
     * @mbggenerated
     */
    private Date uploadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.CHECKINFO
     *
     * @mbggenerated
     */
    private String checkinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.IMAGESOURCE
     *
     * @mbggenerated
     */
    private String imagesource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.create_by
     *
     * @mbggenerated
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.update_by
     *
     * @mbggenerated
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_check_info.DTIME
     *
     * @mbggenerated
     */
    private Date dtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    public CheckInfo(Integer id, Integer userid, Integer eId, Date scantime, Date starttime, Date endtime, Date uploadtime, String checkinfo, String imagesource, Integer status, Date createTime, Long createBy, Date updateTime, Long updateBy, Date dtime) {
        this.id = id;
        this.userid = userid;
        this.eId = eId;
        this.scantime = scantime;
        this.starttime = starttime;
        this.endtime = endtime;
        this.uploadtime = uploadtime;
        this.checkinfo = checkinfo;
        this.imagesource = imagesource;
        this.status = status;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_check_info
     *
     * @mbggenerated
     */
    public CheckInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.ID
     *
     * @return the value of e_check_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.ID
     *
     * @param id the value for e_check_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.USERID
     *
     * @return the value of e_check_info.USERID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.USERID
     *
     * @param userid the value for e_check_info.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.E_ID
     *
     * @return the value of e_check_info.E_ID
     *
     * @mbggenerated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.E_ID
     *
     * @param eId the value for e_check_info.E_ID
     *
     * @mbggenerated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.SCANTIME
     *
     * @return the value of e_check_info.SCANTIME
     *
     * @mbggenerated
     */
    public Date getScantime() {
        return scantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.SCANTIME
     *
     * @param scantime the value for e_check_info.SCANTIME
     *
     * @mbggenerated
     */
    public void setScantime(Date scantime) {
        this.scantime = scantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.STARTTIME
     *
     * @return the value of e_check_info.STARTTIME
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.STARTTIME
     *
     * @param starttime the value for e_check_info.STARTTIME
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.ENDTIME
     *
     * @return the value of e_check_info.ENDTIME
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.ENDTIME
     *
     * @param endtime the value for e_check_info.ENDTIME
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.UPLOADTIME
     *
     * @return the value of e_check_info.UPLOADTIME
     *
     * @mbggenerated
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.UPLOADTIME
     *
     * @param uploadtime the value for e_check_info.UPLOADTIME
     *
     * @mbggenerated
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.CHECKINFO
     *
     * @return the value of e_check_info.CHECKINFO
     *
     * @mbggenerated
     */
    public String getCheckinfo() {
        return checkinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.CHECKINFO
     *
     * @param checkinfo the value for e_check_info.CHECKINFO
     *
     * @mbggenerated
     */
    public void setCheckinfo(String checkinfo) {
        this.checkinfo = checkinfo == null ? null : checkinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.IMAGESOURCE
     *
     * @return the value of e_check_info.IMAGESOURCE
     *
     * @mbggenerated
     */
    public String getImagesource() {
        return imagesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.IMAGESOURCE
     *
     * @param imagesource the value for e_check_info.IMAGESOURCE
     *
     * @mbggenerated
     */
    public void setImagesource(String imagesource) {
        this.imagesource = imagesource == null ? null : imagesource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.STATUS
     *
     * @return the value of e_check_info.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.STATUS
     *
     * @param status the value for e_check_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.create_time
     *
     * @return the value of e_check_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.create_time
     *
     * @param createTime the value for e_check_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.create_by
     *
     * @return the value of e_check_info.create_by
     *
     * @mbggenerated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.create_by
     *
     * @param createBy the value for e_check_info.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.update_time
     *
     * @return the value of e_check_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.update_time
     *
     * @param updateTime the value for e_check_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.update_by
     *
     * @return the value of e_check_info.update_by
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.update_by
     *
     * @param updateBy the value for e_check_info.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_check_info.DTIME
     *
     * @return the value of e_check_info.DTIME
     *
     * @mbggenerated
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_check_info.DTIME
     *
     * @param dtime the value for e_check_info.DTIME
     *
     * @mbggenerated
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }
}