package com.jorchi.elevator.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CheckItemInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public CheckItemInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdIsNull() {
            addCriterion("checkitem_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdIsNotNull() {
            addCriterion("checkitem_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdEqualTo(Integer value) {
            addCriterion("checkitem_id =", value, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdNotEqualTo(Integer value) {
            addCriterion("checkitem_id <>", value, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdGreaterThan(Integer value) {
            addCriterion("checkitem_id >", value, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("checkitem_id >=", value, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdLessThan(Integer value) {
            addCriterion("checkitem_id <", value, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdLessThanOrEqualTo(Integer value) {
            addCriterion("checkitem_id <=", value, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdIn(List<Integer> values) {
            addCriterion("checkitem_id in", values, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdNotIn(List<Integer> values) {
            addCriterion("checkitem_id not in", values, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdBetween(Integer value1, Integer value2) {
            addCriterion("checkitem_id between", value1, value2, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckitemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("checkitem_id not between", value1, value2, "checkitemId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdIsNull() {
            addCriterion("check_info_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdIsNotNull() {
            addCriterion("check_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdEqualTo(Long value) {
            addCriterion("check_info_id =", value, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdNotEqualTo(Long value) {
            addCriterion("check_info_id <>", value, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdGreaterThan(Long value) {
            addCriterion("check_info_id >", value, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("check_info_id >=", value, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdLessThan(Long value) {
            addCriterion("check_info_id <", value, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("check_info_id <=", value, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdIn(List<Long> values) {
            addCriterion("check_info_id in", values, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdNotIn(List<Long> values) {
            addCriterion("check_info_id not in", values, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdBetween(Long value1, Long value2) {
            addCriterion("check_info_id between", value1, value2, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("check_info_id not between", value1, value2, "checkInfoId");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIsNull() {
            addCriterion("check_info is null");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIsNotNull() {
            addCriterion("check_info is not null");
            return (Criteria) this;
        }

        public Criteria andCheckInfoEqualTo(String value) {
            addCriterion("check_info =", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoNotEqualTo(String value) {
            addCriterion("check_info <>", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoGreaterThan(String value) {
            addCriterion("check_info >", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoGreaterThanOrEqualTo(String value) {
            addCriterion("check_info >=", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoLessThan(String value) {
            addCriterion("check_info <", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoLessThanOrEqualTo(String value) {
            addCriterion("check_info <=", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoLike(String value) {
            addCriterion("check_info like", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoNotLike(String value) {
            addCriterion("check_info not like", value, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoIn(List<String> values) {
            addCriterion("check_info in", values, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoNotIn(List<String> values) {
            addCriterion("check_info not in", values, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoBetween(String value1, String value2) {
            addCriterion("check_info between", value1, value2, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andCheckInfoNotBetween(String value1, String value2) {
            addCriterion("check_info not between", value1, value2, "checkInfo");
            return (Criteria) this;
        }

        public Criteria andImageSourceIsNull() {
            addCriterion("image_source is null");
            return (Criteria) this;
        }

        public Criteria andImageSourceIsNotNull() {
            addCriterion("image_source is not null");
            return (Criteria) this;
        }

        public Criteria andImageSourceEqualTo(String value) {
            addCriterion("image_source =", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceNotEqualTo(String value) {
            addCriterion("image_source <>", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceGreaterThan(String value) {
            addCriterion("image_source >", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceGreaterThanOrEqualTo(String value) {
            addCriterion("image_source >=", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceLessThan(String value) {
            addCriterion("image_source <", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceLessThanOrEqualTo(String value) {
            addCriterion("image_source <=", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceLike(String value) {
            addCriterion("image_source like", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceNotLike(String value) {
            addCriterion("image_source not like", value, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceIn(List<String> values) {
            addCriterion("image_source in", values, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceNotIn(List<String> values) {
            addCriterion("image_source not in", values, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceBetween(String value1, String value2) {
            addCriterion("image_source between", value1, value2, "imageSource");
            return (Criteria) this;
        }

        public Criteria andImageSourceNotBetween(String value1, String value2) {
            addCriterion("image_source not between", value1, value2, "imageSource");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Long value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Long value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Long value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Long value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Long value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Long value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Long> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Long> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Long value1, Long value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Long value1, Long value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(Long value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(Long value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(Long value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(Long value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(Long value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(Long value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<Long> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<Long> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(Long value1, Long value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(Long value1, Long value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andProblemIsNull() {
            addCriterion("problem is null");
            return (Criteria) this;
        }

        public Criteria andProblemIsNotNull() {
            addCriterion("problem is not null");
            return (Criteria) this;
        }

        public Criteria andProblemEqualTo(String value) {
            addCriterion("problem =", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemNotEqualTo(String value) {
            addCriterion("problem <>", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemGreaterThan(String value) {
            addCriterion("problem >", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemGreaterThanOrEqualTo(String value) {
            addCriterion("problem >=", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemLessThan(String value) {
            addCriterion("problem <", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemLessThanOrEqualTo(String value) {
            addCriterion("problem <=", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemLike(String value) {
            addCriterion("problem like", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemNotLike(String value) {
            addCriterion("problem not like", value, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemIn(List<String> values) {
            addCriterion("problem in", values, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemNotIn(List<String> values) {
            addCriterion("problem not in", values, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemBetween(String value1, String value2) {
            addCriterion("problem between", value1, value2, "problem");
            return (Criteria) this;
        }

        public Criteria andProblemNotBetween(String value1, String value2) {
            addCriterion("problem not between", value1, value2, "problem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_checkitem_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e_checkitem_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}