package com.jorchi.elevator.orm.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_code
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_code
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_code
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public CodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_code
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andScodeIsNull() {
            addCriterion("SCODE is null");
            return (Criteria) this;
        }

        public Criteria andScodeIsNotNull() {
            addCriterion("SCODE is not null");
            return (Criteria) this;
        }

        public Criteria andScodeEqualTo(String value) {
            addCriterion("SCODE =", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotEqualTo(String value) {
            addCriterion("SCODE <>", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeGreaterThan(String value) {
            addCriterion("SCODE >", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeGreaterThanOrEqualTo(String value) {
            addCriterion("SCODE >=", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLessThan(String value) {
            addCriterion("SCODE <", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLessThanOrEqualTo(String value) {
            addCriterion("SCODE <=", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLike(String value) {
            addCriterion("SCODE like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotLike(String value) {
            addCriterion("SCODE not like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeIn(List<String> values) {
            addCriterion("SCODE in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotIn(List<String> values) {
            addCriterion("SCODE not in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeBetween(String value1, String value2) {
            addCriterion("SCODE between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotBetween(String value1, String value2) {
            addCriterion("SCODE not between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andSnameIsNull() {
            addCriterion("SNAME is null");
            return (Criteria) this;
        }

        public Criteria andSnameIsNotNull() {
            addCriterion("SNAME is not null");
            return (Criteria) this;
        }

        public Criteria andSnameEqualTo(String value) {
            addCriterion("SNAME =", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotEqualTo(String value) {
            addCriterion("SNAME <>", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThan(String value) {
            addCriterion("SNAME >", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThanOrEqualTo(String value) {
            addCriterion("SNAME >=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThan(String value) {
            addCriterion("SNAME <", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThanOrEqualTo(String value) {
            addCriterion("SNAME <=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLike(String value) {
            addCriterion("SNAME like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotLike(String value) {
            addCriterion("SNAME not like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameIn(List<String> values) {
            addCriterion("SNAME in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotIn(List<String> values) {
            addCriterion("SNAME not in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameBetween(String value1, String value2) {
            addCriterion("SNAME between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotBetween(String value1, String value2) {
            addCriterion("SNAME not between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSdescriptionIsNull() {
            addCriterion("SDESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andSdescriptionIsNotNull() {
            addCriterion("SDESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andSdescriptionEqualTo(String value) {
            addCriterion("SDESCRIPTION =", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotEqualTo(String value) {
            addCriterion("SDESCRIPTION <>", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionGreaterThan(String value) {
            addCriterion("SDESCRIPTION >", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("SDESCRIPTION >=", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionLessThan(String value) {
            addCriterion("SDESCRIPTION <", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionLessThanOrEqualTo(String value) {
            addCriterion("SDESCRIPTION <=", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionLike(String value) {
            addCriterion("SDESCRIPTION like", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotLike(String value) {
            addCriterion("SDESCRIPTION not like", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionIn(List<String> values) {
            addCriterion("SDESCRIPTION in", values, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotIn(List<String> values) {
            addCriterion("SDESCRIPTION not in", values, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionBetween(String value1, String value2) {
            addCriterion("SDESCRIPTION between", value1, value2, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotBetween(String value1, String value2) {
            addCriterion("SDESCRIPTION not between", value1, value2, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNull() {
            addCriterion("SREMARK is null");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNotNull() {
            addCriterion("SREMARK is not null");
            return (Criteria) this;
        }

        public Criteria andSremarkEqualTo(String value) {
            addCriterion("SREMARK =", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotEqualTo(String value) {
            addCriterion("SREMARK <>", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkGreaterThan(String value) {
            addCriterion("SREMARK >", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkGreaterThanOrEqualTo(String value) {
            addCriterion("SREMARK >=", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLessThan(String value) {
            addCriterion("SREMARK <", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLessThanOrEqualTo(String value) {
            addCriterion("SREMARK <=", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLike(String value) {
            addCriterion("SREMARK like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotLike(String value) {
            addCriterion("SREMARK not like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkIn(List<String> values) {
            addCriterion("SREMARK in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotIn(List<String> values) {
            addCriterion("SREMARK not in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkBetween(String value1, String value2) {
            addCriterion("SREMARK between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotBetween(String value1, String value2) {
            addCriterion("SREMARK not between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andScreatorIsNull() {
            addCriterion("SCREATOR is null");
            return (Criteria) this;
        }

        public Criteria andScreatorIsNotNull() {
            addCriterion("SCREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andScreatorEqualTo(Long value) {
            addCriterion("SCREATOR =", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotEqualTo(Long value) {
            addCriterion("SCREATOR <>", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorGreaterThan(Long value) {
            addCriterion("SCREATOR >", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("SCREATOR >=", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorLessThan(Long value) {
            addCriterion("SCREATOR <", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorLessThanOrEqualTo(Long value) {
            addCriterion("SCREATOR <=", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorIn(List<Long> values) {
            addCriterion("SCREATOR in", values, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotIn(List<Long> values) {
            addCriterion("SCREATOR not in", values, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorBetween(Long value1, Long value2) {
            addCriterion("SCREATOR between", value1, value2, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotBetween(Long value1, Long value2) {
            addCriterion("SCREATOR not between", value1, value2, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIsNull() {
            addCriterion("SCREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIsNotNull() {
            addCriterion("SCREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andScreatetimeEqualTo(Date value) {
            addCriterion("SCREATETIME =", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotEqualTo(Date value) {
            addCriterion("SCREATETIME <>", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeGreaterThan(Date value) {
            addCriterion("SCREATETIME >", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCREATETIME >=", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeLessThan(Date value) {
            addCriterion("SCREATETIME <", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("SCREATETIME <=", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIn(List<Date> values) {
            addCriterion("SCREATETIME in", values, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotIn(List<Date> values) {
            addCriterion("SCREATETIME not in", values, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeBetween(Date value1, Date value2) {
            addCriterion("SCREATETIME between", value1, value2, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("SCREATETIME not between", value1, value2, "screatetime");
            return (Criteria) this;
        }

        public Criteria andSmodifierIsNull() {
            addCriterion("SMODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andSmodifierIsNotNull() {
            addCriterion("SMODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andSmodifierEqualTo(Long value) {
            addCriterion("SMODIFIER =", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotEqualTo(Long value) {
            addCriterion("SMODIFIER <>", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierGreaterThan(Long value) {
            addCriterion("SMODIFIER >", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierGreaterThanOrEqualTo(Long value) {
            addCriterion("SMODIFIER >=", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierLessThan(Long value) {
            addCriterion("SMODIFIER <", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierLessThanOrEqualTo(Long value) {
            addCriterion("SMODIFIER <=", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierIn(List<Long> values) {
            addCriterion("SMODIFIER in", values, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotIn(List<Long> values) {
            addCriterion("SMODIFIER not in", values, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierBetween(Long value1, Long value2) {
            addCriterion("SMODIFIER between", value1, value2, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotBetween(Long value1, Long value2) {
            addCriterion("SMODIFIER not between", value1, value2, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIsNull() {
            addCriterion("SMODIFYTIME is null");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIsNotNull() {
            addCriterion("SMODIFYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeEqualTo(Date value) {
            addCriterion("SMODIFYTIME =", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotEqualTo(Date value) {
            addCriterion("SMODIFYTIME <>", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeGreaterThan(Date value) {
            addCriterion("SMODIFYTIME >", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMODIFYTIME >=", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeLessThan(Date value) {
            addCriterion("SMODIFYTIME <", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeLessThanOrEqualTo(Date value) {
            addCriterion("SMODIFYTIME <=", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIn(List<Date> values) {
            addCriterion("SMODIFYTIME in", values, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotIn(List<Date> values) {
            addCriterion("SMODIFYTIME not in", values, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeBetween(Date value1, Date value2) {
            addCriterion("SMODIFYTIME between", value1, value2, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotBetween(Date value1, Date value2) {
            addCriterion("SMODIFYTIME not between", value1, value2, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andStypeIsNull() {
            addCriterion("STYPE is null");
            return (Criteria) this;
        }

        public Criteria andStypeIsNotNull() {
            addCriterion("STYPE is not null");
            return (Criteria) this;
        }

        public Criteria andStypeEqualTo(String value) {
            addCriterion("STYPE =", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotEqualTo(String value) {
            addCriterion("STYPE <>", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThan(String value) {
            addCriterion("STYPE >", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThanOrEqualTo(String value) {
            addCriterion("STYPE >=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThan(String value) {
            addCriterion("STYPE <", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThanOrEqualTo(String value) {
            addCriterion("STYPE <=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLike(String value) {
            addCriterion("STYPE like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotLike(String value) {
            addCriterion("STYPE not like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeIn(List<String> values) {
            addCriterion("STYPE in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotIn(List<String> values) {
            addCriterion("STYPE not in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeBetween(String value1, String value2) {
            addCriterion("STYPE between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotBetween(String value1, String value2) {
            addCriterion("STYPE not between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andSstateIsNull() {
            addCriterion("SSTATE is null");
            return (Criteria) this;
        }

        public Criteria andSstateIsNotNull() {
            addCriterion("SSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andSstateEqualTo(Long value) {
            addCriterion("SSTATE =", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotEqualTo(Long value) {
            addCriterion("SSTATE <>", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateGreaterThan(Long value) {
            addCriterion("SSTATE >", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateGreaterThanOrEqualTo(Long value) {
            addCriterion("SSTATE >=", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateLessThan(Long value) {
            addCriterion("SSTATE <", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateLessThanOrEqualTo(Long value) {
            addCriterion("SSTATE <=", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateIn(List<Long> values) {
            addCriterion("SSTATE in", values, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotIn(List<Long> values) {
            addCriterion("SSTATE not in", values, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateBetween(Long value1, Long value2) {
            addCriterion("SSTATE between", value1, value2, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotBetween(Long value1, Long value2) {
            addCriterion("SSTATE not between", value1, value2, "sstate");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNull() {
            addCriterion("SLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNotNull() {
            addCriterion("SLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSlevelEqualTo(String value) {
            addCriterion("SLEVEL =", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotEqualTo(String value) {
            addCriterion("SLEVEL <>", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThan(String value) {
            addCriterion("SLEVEL >", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThanOrEqualTo(String value) {
            addCriterion("SLEVEL >=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThan(String value) {
            addCriterion("SLEVEL <", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThanOrEqualTo(String value) {
            addCriterion("SLEVEL <=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLike(String value) {
            addCriterion("SLEVEL like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotLike(String value) {
            addCriterion("SLEVEL not like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelIn(List<String> values) {
            addCriterion("SLEVEL in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotIn(List<String> values) {
            addCriterion("SLEVEL not in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelBetween(String value1, String value2) {
            addCriterion("SLEVEL between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotBetween(String value1, String value2) {
            addCriterion("SLEVEL not between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSordinalIsNull() {
            addCriterion("SORDINAL is null");
            return (Criteria) this;
        }

        public Criteria andSordinalIsNotNull() {
            addCriterion("SORDINAL is not null");
            return (Criteria) this;
        }

        public Criteria andSordinalEqualTo(String value) {
            addCriterion("SORDINAL =", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotEqualTo(String value) {
            addCriterion("SORDINAL <>", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalGreaterThan(String value) {
            addCriterion("SORDINAL >", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalGreaterThanOrEqualTo(String value) {
            addCriterion("SORDINAL >=", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLessThan(String value) {
            addCriterion("SORDINAL <", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLessThanOrEqualTo(String value) {
            addCriterion("SORDINAL <=", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLike(String value) {
            addCriterion("SORDINAL like", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotLike(String value) {
            addCriterion("SORDINAL not like", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalIn(List<String> values) {
            addCriterion("SORDINAL in", values, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotIn(List<String> values) {
            addCriterion("SORDINAL not in", values, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalBetween(String value1, String value2) {
            addCriterion("SORDINAL between", value1, value2, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotBetween(String value1, String value2) {
            addCriterion("SORDINAL not between", value1, value2, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSsystemIsNull() {
            addCriterion("SSYSTEM is null");
            return (Criteria) this;
        }

        public Criteria andSsystemIsNotNull() {
            addCriterion("SSYSTEM is not null");
            return (Criteria) this;
        }

        public Criteria andSsystemEqualTo(String value) {
            addCriterion("SSYSTEM =", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotEqualTo(String value) {
            addCriterion("SSYSTEM <>", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemGreaterThan(String value) {
            addCriterion("SSYSTEM >", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemGreaterThanOrEqualTo(String value) {
            addCriterion("SSYSTEM >=", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLessThan(String value) {
            addCriterion("SSYSTEM <", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLessThanOrEqualTo(String value) {
            addCriterion("SSYSTEM <=", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLike(String value) {
            addCriterion("SSYSTEM like", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotLike(String value) {
            addCriterion("SSYSTEM not like", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemIn(List<String> values) {
            addCriterion("SSYSTEM in", values, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotIn(List<String> values) {
            addCriterion("SSYSTEM not in", values, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemBetween(String value1, String value2) {
            addCriterion("SSYSTEM between", value1, value2, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotBetween(String value1, String value2) {
            addCriterion("SSYSTEM not between", value1, value2, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSenabledIsNull() {
            addCriterion("SENABLED is null");
            return (Criteria) this;
        }

        public Criteria andSenabledIsNotNull() {
            addCriterion("SENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andSenabledEqualTo(String value) {
            addCriterion("SENABLED =", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotEqualTo(String value) {
            addCriterion("SENABLED <>", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledGreaterThan(String value) {
            addCriterion("SENABLED >", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledGreaterThanOrEqualTo(String value) {
            addCriterion("SENABLED >=", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLessThan(String value) {
            addCriterion("SENABLED <", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLessThanOrEqualTo(String value) {
            addCriterion("SENABLED <=", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLike(String value) {
            addCriterion("SENABLED like", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotLike(String value) {
            addCriterion("SENABLED not like", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledIn(List<String> values) {
            addCriterion("SENABLED in", values, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotIn(List<String> values) {
            addCriterion("SENABLED not in", values, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledBetween(String value1, String value2) {
            addCriterion("SENABLED between", value1, value2, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotBetween(String value1, String value2) {
            addCriterion("SENABLED not between", value1, value2, "senabled");
            return (Criteria) this;
        }

        public Criteria andGpsaddressIsNull() {
            addCriterion("GPSADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andGpsaddressIsNotNull() {
            addCriterion("GPSADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andGpsaddressEqualTo(String value) {
            addCriterion("GPSADDRESS =", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressNotEqualTo(String value) {
            addCriterion("GPSADDRESS <>", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressGreaterThan(String value) {
            addCriterion("GPSADDRESS >", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressGreaterThanOrEqualTo(String value) {
            addCriterion("GPSADDRESS >=", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressLessThan(String value) {
            addCriterion("GPSADDRESS <", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressLessThanOrEqualTo(String value) {
            addCriterion("GPSADDRESS <=", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressLike(String value) {
            addCriterion("GPSADDRESS like", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressNotLike(String value) {
            addCriterion("GPSADDRESS not like", value, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressIn(List<String> values) {
            addCriterion("GPSADDRESS in", values, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressNotIn(List<String> values) {
            addCriterion("GPSADDRESS not in", values, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressBetween(String value1, String value2) {
            addCriterion("GPSADDRESS between", value1, value2, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andGpsaddressNotBetween(String value1, String value2) {
            addCriterion("GPSADDRESS not between", value1, value2, "gpsaddress");
            return (Criteria) this;
        }

        public Criteria andUrlimgIsNull() {
            addCriterion("URLIMG is null");
            return (Criteria) this;
        }

        public Criteria andUrlimgIsNotNull() {
            addCriterion("URLIMG is not null");
            return (Criteria) this;
        }

        public Criteria andUrlimgEqualTo(String value) {
            addCriterion("URLIMG =", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgNotEqualTo(String value) {
            addCriterion("URLIMG <>", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgGreaterThan(String value) {
            addCriterion("URLIMG >", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgGreaterThanOrEqualTo(String value) {
            addCriterion("URLIMG >=", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgLessThan(String value) {
            addCriterion("URLIMG <", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgLessThanOrEqualTo(String value) {
            addCriterion("URLIMG <=", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgLike(String value) {
            addCriterion("URLIMG like", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgNotLike(String value) {
            addCriterion("URLIMG not like", value, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgIn(List<String> values) {
            addCriterion("URLIMG in", values, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgNotIn(List<String> values) {
            addCriterion("URLIMG not in", values, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgBetween(String value1, String value2) {
            addCriterion("URLIMG between", value1, value2, "urlimg");
            return (Criteria) this;
        }

        public Criteria andUrlimgNotBetween(String value1, String value2) {
            addCriterion("URLIMG not between", value1, value2, "urlimg");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("PARENTID is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("PARENTID is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Long value) {
            addCriterion("PARENTID =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Long value) {
            addCriterion("PARENTID <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Long value) {
            addCriterion("PARENTID >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENTID >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Long value) {
            addCriterion("PARENTID <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Long value) {
            addCriterion("PARENTID <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Long> values) {
            addCriterion("PARENTID in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Long> values) {
            addCriterion("PARENTID not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Long value1, Long value2) {
            addCriterion("PARENTID between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Long value1, Long value2) {
            addCriterion("PARENTID not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidIsNull() {
            addCriterion("CODETYPEID is null");
            return (Criteria) this;
        }

        public Criteria andCodetypeidIsNotNull() {
            addCriterion("CODETYPEID is not null");
            return (Criteria) this;
        }

        public Criteria andCodetypeidEqualTo(Long value) {
            addCriterion("CODETYPEID =", value, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidNotEqualTo(Long value) {
            addCriterion("CODETYPEID <>", value, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidGreaterThan(Long value) {
            addCriterion("CODETYPEID >", value, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidGreaterThanOrEqualTo(Long value) {
            addCriterion("CODETYPEID >=", value, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidLessThan(Long value) {
            addCriterion("CODETYPEID <", value, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidLessThanOrEqualTo(Long value) {
            addCriterion("CODETYPEID <=", value, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidIn(List<Long> values) {
            addCriterion("CODETYPEID in", values, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidNotIn(List<Long> values) {
            addCriterion("CODETYPEID not in", values, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidBetween(Long value1, Long value2) {
            addCriterion("CODETYPEID between", value1, value2, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andCodetypeidNotBetween(Long value1, Long value2) {
            addCriterion("CODETYPEID not between", value1, value2, "codetypeid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andGpsxIsNull() {
            addCriterion("GPSX is null");
            return (Criteria) this;
        }

        public Criteria andGpsxIsNotNull() {
            addCriterion("GPSX is not null");
            return (Criteria) this;
        }

        public Criteria andGpsxEqualTo(BigDecimal value) {
            addCriterion("GPSX =", value, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxNotEqualTo(BigDecimal value) {
            addCriterion("GPSX <>", value, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxGreaterThan(BigDecimal value) {
            addCriterion("GPSX >", value, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GPSX >=", value, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxLessThan(BigDecimal value) {
            addCriterion("GPSX <", value, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GPSX <=", value, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxIn(List<BigDecimal> values) {
            addCriterion("GPSX in", values, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxNotIn(List<BigDecimal> values) {
            addCriterion("GPSX not in", values, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GPSX between", value1, value2, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GPSX not between", value1, value2, "gpsx");
            return (Criteria) this;
        }

        public Criteria andGpsyIsNull() {
            addCriterion("GPSY is null");
            return (Criteria) this;
        }

        public Criteria andGpsyIsNotNull() {
            addCriterion("GPSY is not null");
            return (Criteria) this;
        }

        public Criteria andGpsyEqualTo(BigDecimal value) {
            addCriterion("GPSY =", value, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyNotEqualTo(BigDecimal value) {
            addCriterion("GPSY <>", value, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyGreaterThan(BigDecimal value) {
            addCriterion("GPSY >", value, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GPSY >=", value, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyLessThan(BigDecimal value) {
            addCriterion("GPSY <", value, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GPSY <=", value, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyIn(List<BigDecimal> values) {
            addCriterion("GPSY in", values, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyNotIn(List<BigDecimal> values) {
            addCriterion("GPSY not in", values, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GPSY between", value1, value2, "gpsy");
            return (Criteria) this;
        }

        public Criteria andGpsyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GPSY not between", value1, value2, "gpsy");
            return (Criteria) this;
        }

        public Criteria andSyearIsNull() {
            addCriterion("SYEAR is null");
            return (Criteria) this;
        }

        public Criteria andSyearIsNotNull() {
            addCriterion("SYEAR is not null");
            return (Criteria) this;
        }

        public Criteria andSyearEqualTo(String value) {
            addCriterion("SYEAR =", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearNotEqualTo(String value) {
            addCriterion("SYEAR <>", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearGreaterThan(String value) {
            addCriterion("SYEAR >", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearGreaterThanOrEqualTo(String value) {
            addCriterion("SYEAR >=", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearLessThan(String value) {
            addCriterion("SYEAR <", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearLessThanOrEqualTo(String value) {
            addCriterion("SYEAR <=", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearLike(String value) {
            addCriterion("SYEAR like", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearNotLike(String value) {
            addCriterion("SYEAR not like", value, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearIn(List<String> values) {
            addCriterion("SYEAR in", values, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearNotIn(List<String> values) {
            addCriterion("SYEAR not in", values, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearBetween(String value1, String value2) {
            addCriterion("SYEAR between", value1, value2, "syear");
            return (Criteria) this;
        }

        public Criteria andSyearNotBetween(String value1, String value2) {
            addCriterion("SYEAR not between", value1, value2, "syear");
            return (Criteria) this;
        }

        public Criteria andUfcodeIsNull() {
            addCriterion("UFCODE is null");
            return (Criteria) this;
        }

        public Criteria andUfcodeIsNotNull() {
            addCriterion("UFCODE is not null");
            return (Criteria) this;
        }

        public Criteria andUfcodeEqualTo(String value) {
            addCriterion("UFCODE =", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeNotEqualTo(String value) {
            addCriterion("UFCODE <>", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeGreaterThan(String value) {
            addCriterion("UFCODE >", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeGreaterThanOrEqualTo(String value) {
            addCriterion("UFCODE >=", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeLessThan(String value) {
            addCriterion("UFCODE <", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeLessThanOrEqualTo(String value) {
            addCriterion("UFCODE <=", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeLike(String value) {
            addCriterion("UFCODE like", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeNotLike(String value) {
            addCriterion("UFCODE not like", value, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeIn(List<String> values) {
            addCriterion("UFCODE in", values, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeNotIn(List<String> values) {
            addCriterion("UFCODE not in", values, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeBetween(String value1, String value2) {
            addCriterion("UFCODE between", value1, value2, "ufcode");
            return (Criteria) this;
        }

        public Criteria andUfcodeNotBetween(String value1, String value2) {
            addCriterion("UFCODE not between", value1, value2, "ufcode");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNull() {
            addCriterion("HOUSEID is null");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNotNull() {
            addCriterion("HOUSEID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseidEqualTo(Integer value) {
            addCriterion("HOUSEID =", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotEqualTo(Integer value) {
            addCriterion("HOUSEID <>", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThan(Integer value) {
            addCriterion("HOUSEID >", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThanOrEqualTo(Integer value) {
            addCriterion("HOUSEID >=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThan(Integer value) {
            addCriterion("HOUSEID <", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThanOrEqualTo(Integer value) {
            addCriterion("HOUSEID <=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidIn(List<Integer> values) {
            addCriterion("HOUSEID in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotIn(List<Integer> values) {
            addCriterion("HOUSEID not in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidBetween(Integer value1, Integer value2) {
            addCriterion("HOUSEID between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotBetween(Integer value1, Integer value2) {
            addCriterion("HOUSEID not between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andPackageidIsNull() {
            addCriterion("PACKAGEID is null");
            return (Criteria) this;
        }

        public Criteria andPackageidIsNotNull() {
            addCriterion("PACKAGEID is not null");
            return (Criteria) this;
        }

        public Criteria andPackageidEqualTo(Long value) {
            addCriterion("PACKAGEID =", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidNotEqualTo(Long value) {
            addCriterion("PACKAGEID <>", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidGreaterThan(Long value) {
            addCriterion("PACKAGEID >", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidGreaterThanOrEqualTo(Long value) {
            addCriterion("PACKAGEID >=", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidLessThan(Long value) {
            addCriterion("PACKAGEID <", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidLessThanOrEqualTo(Long value) {
            addCriterion("PACKAGEID <=", value, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidIn(List<Long> values) {
            addCriterion("PACKAGEID in", values, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidNotIn(List<Long> values) {
            addCriterion("PACKAGEID not in", values, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidBetween(Long value1, Long value2) {
            addCriterion("PACKAGEID between", value1, value2, "packageid");
            return (Criteria) this;
        }

        public Criteria andPackageidNotBetween(Long value1, Long value2) {
            addCriterion("PACKAGEID not between", value1, value2, "packageid");
            return (Criteria) this;
        }

        public Criteria andElevatoridIsNull() {
            addCriterion("ELEVATORID is null");
            return (Criteria) this;
        }

        public Criteria andElevatoridIsNotNull() {
            addCriterion("ELEVATORID is not null");
            return (Criteria) this;
        }

        public Criteria andElevatoridEqualTo(Long value) {
            addCriterion("ELEVATORID =", value, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridNotEqualTo(Long value) {
            addCriterion("ELEVATORID <>", value, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridGreaterThan(Long value) {
            addCriterion("ELEVATORID >", value, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridGreaterThanOrEqualTo(Long value) {
            addCriterion("ELEVATORID >=", value, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridLessThan(Long value) {
            addCriterion("ELEVATORID <", value, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridLessThanOrEqualTo(Long value) {
            addCriterion("ELEVATORID <=", value, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridIn(List<Long> values) {
            addCriterion("ELEVATORID in", values, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridNotIn(List<Long> values) {
            addCriterion("ELEVATORID not in", values, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridBetween(Long value1, Long value2) {
            addCriterion("ELEVATORID between", value1, value2, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andElevatoridNotBetween(Long value1, Long value2) {
            addCriterion("ELEVATORID not between", value1, value2, "elevatorid");
            return (Criteria) this;
        }

        public Criteria andRegcodeIsNull() {
            addCriterion("REGCODE is null");
            return (Criteria) this;
        }

        public Criteria andRegcodeIsNotNull() {
            addCriterion("REGCODE is not null");
            return (Criteria) this;
        }

        public Criteria andRegcodeEqualTo(String value) {
            addCriterion("REGCODE =", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotEqualTo(String value) {
            addCriterion("REGCODE <>", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeGreaterThan(String value) {
            addCriterion("REGCODE >", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeGreaterThanOrEqualTo(String value) {
            addCriterion("REGCODE >=", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeLessThan(String value) {
            addCriterion("REGCODE <", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeLessThanOrEqualTo(String value) {
            addCriterion("REGCODE <=", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeLike(String value) {
            addCriterion("REGCODE like", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotLike(String value) {
            addCriterion("REGCODE not like", value, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeIn(List<String> values) {
            addCriterion("REGCODE in", values, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotIn(List<String> values) {
            addCriterion("REGCODE not in", values, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeBetween(String value1, String value2) {
            addCriterion("REGCODE between", value1, value2, "regcode");
            return (Criteria) this;
        }

        public Criteria andRegcodeNotBetween(String value1, String value2) {
            addCriterion("REGCODE not between", value1, value2, "regcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_code
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}