package com.jorchi.elevator.orm.model;

import java.util.Date;

public class codeElevator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SCODE
     *
     * @mbggenerated
     */
    private String scode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SNAME
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SREMARK
     *
     * @mbggenerated
     */
    private String sremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SCREATOR
     *
     * @mbggenerated
     */
    private Long screator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SCREATETIME
     *
     * @mbggenerated
     */
    private Date screatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SMODIFIER
     *
     * @mbggenerated
     */
    private Long smodifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SMODIFYTIME
     *
     * @mbggenerated
     */
    private Date smodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.STYPE
     *
     * @mbggenerated
     */
    private String stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SSYSTEM
     *
     * @mbggenerated
     */
    private String ssystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SENABLED
     *
     * @mbggenerated
     */
    private String senabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SSTATE
     *
     * @mbggenerated
     */
    private Long sstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SLEVEL
     *
     * @mbggenerated
     */
    private String slevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SORDINAL
     *
     * @mbggenerated
     */
    private String sordinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.PROPERTYCOMP
     *
     * @mbggenerated
     */
    private String propertycomp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.VILLAGENAME
     *
     * @mbggenerated
     */
    private String villagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ELEVATORBRAND
     *
     * @mbggenerated
     */
    private String elevatorbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ELEVATORMODEL
     *
     * @mbggenerated
     */
    private String elevatormodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.LOADWEIGHT
     *
     * @mbggenerated
     */
    private String loadweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SPEED
     *
     * @mbggenerated
     */
    private String speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.LAYERNUMBER
     *
     * @mbggenerated
     */
    private String layernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.DELIVERDATE
     *
     * @mbggenerated
     */
    private Date deliverdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.OCCASION
     *
     * @mbggenerated
     */
    private String occasion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.INSPECTIONDATE
     *
     * @mbggenerated
     */
    private Date inspectiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.IMPORTORNOT
     *
     * @mbggenerated
     */
    private String importornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.PRODUCTIONNUMBER
     *
     * @mbggenerated
     */
    private String productionnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.COMPUTERROOM
     *
     * @mbggenerated
     */
    private String computerroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ELEVATORTYPE
     *
     * @mbggenerated
     */
    private String elevatortype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.CATEGORY
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SPECIALPURP
     *
     * @mbggenerated
     */
    private String specialpurp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.CODEID
     *
     * @mbggenerated
     */
    private Integer codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.SEEDID
     *
     * @mbggenerated
     */
    private String seedid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ISNEED
     *
     * @mbggenerated
     */
    private String isneed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ISEXTEND
     *
     * @mbggenerated
     */
    private String isextend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code_elevator.ZCDM
     *
     * @mbggenerated
     */
    private String zcdm;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public codeElevator(Integer id, String scode, String sname, String sremark, Long screator, Date screatetime, Long smodifier, Date smodifytime, String stype, String ssystem, String senabled, Long sstate, String slevel, String sordinal, String propertycomp, String villagename, String elevatorbrand, String elevatormodel, String loadweight, String speed, String layernumber, Date deliverdate, String occasion, Date inspectiondate, String importornot, String productionnumber, String computerroom, String elevatortype, String category, String specialpurp, Integer codeid, String seedid, String isneed, String isextend, String zcdm) {
        this.id = id;
        this.scode = scode;
        this.sname = sname;
        this.sremark = sremark;
        this.screator = screator;
        this.screatetime = screatetime;
        this.smodifier = smodifier;
        this.smodifytime = smodifytime;
        this.stype = stype;
        this.ssystem = ssystem;
        this.senabled = senabled;
        this.sstate = sstate;
        this.slevel = slevel;
        this.sordinal = sordinal;
        this.propertycomp = propertycomp;
        this.villagename = villagename;
        this.elevatorbrand = elevatorbrand;
        this.elevatormodel = elevatormodel;
        this.loadweight = loadweight;
        this.speed = speed;
        this.layernumber = layernumber;
        this.deliverdate = deliverdate;
        this.occasion = occasion;
        this.inspectiondate = inspectiondate;
        this.importornot = importornot;
        this.productionnumber = productionnumber;
        this.computerroom = computerroom;
        this.elevatortype = elevatortype;
        this.category = category;
        this.specialpurp = specialpurp;
        this.codeid = codeid;
        this.seedid = seedid;
        this.isneed = isneed;
        this.isextend = isextend;
        this.zcdm = zcdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public codeElevator() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ID
     *
     * @return the value of u_code_elevator.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ID
     *
     * @param id the value for u_code_elevator.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SCODE
     *
     * @return the value of u_code_elevator.SCODE
     *
     * @mbggenerated
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SCODE
     *
     * @param scode the value for u_code_elevator.SCODE
     *
     * @mbggenerated
     */
    public void setScode(String scode) {
        this.scode = scode == null ? null : scode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SNAME
     *
     * @return the value of u_code_elevator.SNAME
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SNAME
     *
     * @param sname the value for u_code_elevator.SNAME
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SREMARK
     *
     * @return the value of u_code_elevator.SREMARK
     *
     * @mbggenerated
     */
    public String getSremark() {
        return sremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SREMARK
     *
     * @param sremark the value for u_code_elevator.SREMARK
     *
     * @mbggenerated
     */
    public void setSremark(String sremark) {
        this.sremark = sremark == null ? null : sremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SCREATOR
     *
     * @return the value of u_code_elevator.SCREATOR
     *
     * @mbggenerated
     */
    public Long getScreator() {
        return screator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SCREATOR
     *
     * @param screator the value for u_code_elevator.SCREATOR
     *
     * @mbggenerated
     */
    public void setScreator(Long screator) {
        this.screator = screator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SCREATETIME
     *
     * @return the value of u_code_elevator.SCREATETIME
     *
     * @mbggenerated
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SCREATETIME
     *
     * @param screatetime the value for u_code_elevator.SCREATETIME
     *
     * @mbggenerated
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SMODIFIER
     *
     * @return the value of u_code_elevator.SMODIFIER
     *
     * @mbggenerated
     */
    public Long getSmodifier() {
        return smodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SMODIFIER
     *
     * @param smodifier the value for u_code_elevator.SMODIFIER
     *
     * @mbggenerated
     */
    public void setSmodifier(Long smodifier) {
        this.smodifier = smodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SMODIFYTIME
     *
     * @return the value of u_code_elevator.SMODIFYTIME
     *
     * @mbggenerated
     */
    public Date getSmodifytime() {
        return smodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SMODIFYTIME
     *
     * @param smodifytime the value for u_code_elevator.SMODIFYTIME
     *
     * @mbggenerated
     */
    public void setSmodifytime(Date smodifytime) {
        this.smodifytime = smodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.STYPE
     *
     * @return the value of u_code_elevator.STYPE
     *
     * @mbggenerated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.STYPE
     *
     * @param stype the value for u_code_elevator.STYPE
     *
     * @mbggenerated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SSYSTEM
     *
     * @return the value of u_code_elevator.SSYSTEM
     *
     * @mbggenerated
     */
    public String getSsystem() {
        return ssystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SSYSTEM
     *
     * @param ssystem the value for u_code_elevator.SSYSTEM
     *
     * @mbggenerated
     */
    public void setSsystem(String ssystem) {
        this.ssystem = ssystem == null ? null : ssystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SENABLED
     *
     * @return the value of u_code_elevator.SENABLED
     *
     * @mbggenerated
     */
    public String getSenabled() {
        return senabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SENABLED
     *
     * @param senabled the value for u_code_elevator.SENABLED
     *
     * @mbggenerated
     */
    public void setSenabled(String senabled) {
        this.senabled = senabled == null ? null : senabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SSTATE
     *
     * @return the value of u_code_elevator.SSTATE
     *
     * @mbggenerated
     */
    public Long getSstate() {
        return sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SSTATE
     *
     * @param sstate the value for u_code_elevator.SSTATE
     *
     * @mbggenerated
     */
    public void setSstate(Long sstate) {
        this.sstate = sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SLEVEL
     *
     * @return the value of u_code_elevator.SLEVEL
     *
     * @mbggenerated
     */
    public String getSlevel() {
        return slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SLEVEL
     *
     * @param slevel the value for u_code_elevator.SLEVEL
     *
     * @mbggenerated
     */
    public void setSlevel(String slevel) {
        this.slevel = slevel == null ? null : slevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SORDINAL
     *
     * @return the value of u_code_elevator.SORDINAL
     *
     * @mbggenerated
     */
    public String getSordinal() {
        return sordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SORDINAL
     *
     * @param sordinal the value for u_code_elevator.SORDINAL
     *
     * @mbggenerated
     */
    public void setSordinal(String sordinal) {
        this.sordinal = sordinal == null ? null : sordinal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.PROPERTYCOMP
     *
     * @return the value of u_code_elevator.PROPERTYCOMP
     *
     * @mbggenerated
     */
    public String getPropertycomp() {
        return propertycomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.PROPERTYCOMP
     *
     * @param propertycomp the value for u_code_elevator.PROPERTYCOMP
     *
     * @mbggenerated
     */
    public void setPropertycomp(String propertycomp) {
        this.propertycomp = propertycomp == null ? null : propertycomp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.VILLAGENAME
     *
     * @return the value of u_code_elevator.VILLAGENAME
     *
     * @mbggenerated
     */
    public String getVillagename() {
        return villagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.VILLAGENAME
     *
     * @param villagename the value for u_code_elevator.VILLAGENAME
     *
     * @mbggenerated
     */
    public void setVillagename(String villagename) {
        this.villagename = villagename == null ? null : villagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ELEVATORBRAND
     *
     * @return the value of u_code_elevator.ELEVATORBRAND
     *
     * @mbggenerated
     */
    public String getElevatorbrand() {
        return elevatorbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ELEVATORBRAND
     *
     * @param elevatorbrand the value for u_code_elevator.ELEVATORBRAND
     *
     * @mbggenerated
     */
    public void setElevatorbrand(String elevatorbrand) {
        this.elevatorbrand = elevatorbrand == null ? null : elevatorbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ELEVATORMODEL
     *
     * @return the value of u_code_elevator.ELEVATORMODEL
     *
     * @mbggenerated
     */
    public String getElevatormodel() {
        return elevatormodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ELEVATORMODEL
     *
     * @param elevatormodel the value for u_code_elevator.ELEVATORMODEL
     *
     * @mbggenerated
     */
    public void setElevatormodel(String elevatormodel) {
        this.elevatormodel = elevatormodel == null ? null : elevatormodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.LOADWEIGHT
     *
     * @return the value of u_code_elevator.LOADWEIGHT
     *
     * @mbggenerated
     */
    public String getLoadweight() {
        return loadweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.LOADWEIGHT
     *
     * @param loadweight the value for u_code_elevator.LOADWEIGHT
     *
     * @mbggenerated
     */
    public void setLoadweight(String loadweight) {
        this.loadweight = loadweight == null ? null : loadweight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SPEED
     *
     * @return the value of u_code_elevator.SPEED
     *
     * @mbggenerated
     */
    public String getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SPEED
     *
     * @param speed the value for u_code_elevator.SPEED
     *
     * @mbggenerated
     */
    public void setSpeed(String speed) {
        this.speed = speed == null ? null : speed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.LAYERNUMBER
     *
     * @return the value of u_code_elevator.LAYERNUMBER
     *
     * @mbggenerated
     */
    public String getLayernumber() {
        return layernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.LAYERNUMBER
     *
     * @param layernumber the value for u_code_elevator.LAYERNUMBER
     *
     * @mbggenerated
     */
    public void setLayernumber(String layernumber) {
        this.layernumber = layernumber == null ? null : layernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.DELIVERDATE
     *
     * @return the value of u_code_elevator.DELIVERDATE
     *
     * @mbggenerated
     */
    public Date getDeliverdate() {
        return deliverdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.DELIVERDATE
     *
     * @param deliverdate the value for u_code_elevator.DELIVERDATE
     *
     * @mbggenerated
     */
    public void setDeliverdate(Date deliverdate) {
        this.deliverdate = deliverdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.OCCASION
     *
     * @return the value of u_code_elevator.OCCASION
     *
     * @mbggenerated
     */
    public String getOccasion() {
        return occasion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.OCCASION
     *
     * @param occasion the value for u_code_elevator.OCCASION
     *
     * @mbggenerated
     */
    public void setOccasion(String occasion) {
        this.occasion = occasion == null ? null : occasion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.INSPECTIONDATE
     *
     * @return the value of u_code_elevator.INSPECTIONDATE
     *
     * @mbggenerated
     */
    public Date getInspectiondate() {
        return inspectiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.INSPECTIONDATE
     *
     * @param inspectiondate the value for u_code_elevator.INSPECTIONDATE
     *
     * @mbggenerated
     */
    public void setInspectiondate(Date inspectiondate) {
        this.inspectiondate = inspectiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.IMPORTORNOT
     *
     * @return the value of u_code_elevator.IMPORTORNOT
     *
     * @mbggenerated
     */
    public String getImportornot() {
        return importornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.IMPORTORNOT
     *
     * @param importornot the value for u_code_elevator.IMPORTORNOT
     *
     * @mbggenerated
     */
    public void setImportornot(String importornot) {
        this.importornot = importornot == null ? null : importornot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.PRODUCTIONNUMBER
     *
     * @return the value of u_code_elevator.PRODUCTIONNUMBER
     *
     * @mbggenerated
     */
    public String getProductionnumber() {
        return productionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.PRODUCTIONNUMBER
     *
     * @param productionnumber the value for u_code_elevator.PRODUCTIONNUMBER
     *
     * @mbggenerated
     */
    public void setProductionnumber(String productionnumber) {
        this.productionnumber = productionnumber == null ? null : productionnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.COMPUTERROOM
     *
     * @return the value of u_code_elevator.COMPUTERROOM
     *
     * @mbggenerated
     */
    public String getComputerroom() {
        return computerroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.COMPUTERROOM
     *
     * @param computerroom the value for u_code_elevator.COMPUTERROOM
     *
     * @mbggenerated
     */
    public void setComputerroom(String computerroom) {
        this.computerroom = computerroom == null ? null : computerroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ELEVATORTYPE
     *
     * @return the value of u_code_elevator.ELEVATORTYPE
     *
     * @mbggenerated
     */
    public String getElevatortype() {
        return elevatortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ELEVATORTYPE
     *
     * @param elevatortype the value for u_code_elevator.ELEVATORTYPE
     *
     * @mbggenerated
     */
    public void setElevatortype(String elevatortype) {
        this.elevatortype = elevatortype == null ? null : elevatortype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.CATEGORY
     *
     * @return the value of u_code_elevator.CATEGORY
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.CATEGORY
     *
     * @param category the value for u_code_elevator.CATEGORY
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SPECIALPURP
     *
     * @return the value of u_code_elevator.SPECIALPURP
     *
     * @mbggenerated
     */
    public String getSpecialpurp() {
        return specialpurp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SPECIALPURP
     *
     * @param specialpurp the value for u_code_elevator.SPECIALPURP
     *
     * @mbggenerated
     */
    public void setSpecialpurp(String specialpurp) {
        this.specialpurp = specialpurp == null ? null : specialpurp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.CODEID
     *
     * @return the value of u_code_elevator.CODEID
     *
     * @mbggenerated
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.CODEID
     *
     * @param codeid the value for u_code_elevator.CODEID
     *
     * @mbggenerated
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.SEEDID
     *
     * @return the value of u_code_elevator.SEEDID
     *
     * @mbggenerated
     */
    public String getSeedid() {
        return seedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.SEEDID
     *
     * @param seedid the value for u_code_elevator.SEEDID
     *
     * @mbggenerated
     */
    public void setSeedid(String seedid) {
        this.seedid = seedid == null ? null : seedid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ISNEED
     *
     * @return the value of u_code_elevator.ISNEED
     *
     * @mbggenerated
     */
    public String getIsneed() {
        return isneed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ISNEED
     *
     * @param isneed the value for u_code_elevator.ISNEED
     *
     * @mbggenerated
     */
    public void setIsneed(String isneed) {
        this.isneed = isneed == null ? null : isneed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ISEXTEND
     *
     * @return the value of u_code_elevator.ISEXTEND
     *
     * @mbggenerated
     */
    public String getIsextend() {
        return isextend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ISEXTEND
     *
     * @param isextend the value for u_code_elevator.ISEXTEND
     *
     * @mbggenerated
     */
    public void setIsextend(String isextend) {
        this.isextend = isextend == null ? null : isextend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code_elevator.ZCDM
     *
     * @return the value of u_code_elevator.ZCDM
     *
     * @mbggenerated
     */
    public String getZcdm() {
        return zcdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code_elevator.ZCDM
     *
     * @param zcdm the value for u_code_elevator.ZCDM
     *
     * @mbggenerated
     */
    public void setZcdm(String zcdm) {
        this.zcdm = zcdm == null ? null : zcdm.trim();
    }
}