package com.jorchi.elevator.orm.model;

import java.math.BigDecimal;
import java.util.Date;

public class Code {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SCODE
     *
     * @mbggenerated
     */
    private String scode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SNAME
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SDESCRIPTION
     *
     * @mbggenerated
     */
    private String sdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SREMARK
     *
     * @mbggenerated
     */
    private String sremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SCREATOR
     *
     * @mbggenerated
     */
    private Long screator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SCREATETIME
     *
     * @mbggenerated
     */
    private Date screatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SMODIFIER
     *
     * @mbggenerated
     */
    private Long smodifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SMODIFYTIME
     *
     * @mbggenerated
     */
    private Date smodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.STYPE
     *
     * @mbggenerated
     */
    private String stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SSTATE
     *
     * @mbggenerated
     */
    private Long sstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SLEVEL
     *
     * @mbggenerated
     */
    private String slevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SORDINAL
     *
     * @mbggenerated
     */
    private String sordinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SSYSTEM
     *
     * @mbggenerated
     */
    private String ssystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SENABLED
     *
     * @mbggenerated
     */
    private String senabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.GPSADDRESS
     *
     * @mbggenerated
     */
    private String gpsaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.URLIMG
     *
     * @mbggenerated
     */
    private String urlimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.PARENTID
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.CODETYPEID
     *
     * @mbggenerated
     */
    private Long codetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.USERID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.GPSX
     *
     * @mbggenerated
     */
    private BigDecimal gpsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.GPSY
     *
     * @mbggenerated
     */
    private BigDecimal gpsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.SYEAR
     *
     * @mbggenerated
     */
    private String syear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.UFCODE
     *
     * @mbggenerated
     */
    private String ufcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.HOUSEID
     *
     * @mbggenerated
     */
    private Integer houseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.PACKAGEID
     *
     * @mbggenerated
     */
    private Long packageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.ELEVATORID
     *
     * @mbggenerated
     */
    private Long elevatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.REGCODE
     *
     * @mbggenerated
     */
    private String regcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_code.TEXTCONTENT
     *
     * @mbggenerated
     */
    private String textcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public Code(Integer id, String scode, String sname, String sdescription, String sremark, Long screator, Date screatetime, Long smodifier, Date smodifytime, String stype, Long sstate, String slevel, String sordinal, String ssystem, String senabled, String gpsaddress, String urlimg, Long parentid, Long codetypeid, Long userid, BigDecimal gpsx, BigDecimal gpsy, String syear, String ufcode, Integer houseid, Long packageid, Long elevatorid, String regcode, String textcontent) {
        this.id = id;
        this.scode = scode;
        this.sname = sname;
        this.sdescription = sdescription;
        this.sremark = sremark;
        this.screator = screator;
        this.screatetime = screatetime;
        this.smodifier = smodifier;
        this.smodifytime = smodifytime;
        this.stype = stype;
        this.sstate = sstate;
        this.slevel = slevel;
        this.sordinal = sordinal;
        this.ssystem = ssystem;
        this.senabled = senabled;
        this.gpsaddress = gpsaddress;
        this.urlimg = urlimg;
        this.parentid = parentid;
        this.codetypeid = codetypeid;
        this.userid = userid;
        this.gpsx = gpsx;
        this.gpsy = gpsy;
        this.syear = syear;
        this.ufcode = ufcode;
        this.houseid = houseid;
        this.packageid = packageid;
        this.elevatorid = elevatorid;
        this.regcode = regcode;
        this.textcontent = textcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code
     *
     * @mbggenerated
     */
    public Code() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.ID
     *
     * @return the value of u_code.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.ID
     *
     * @param id the value for u_code.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SCODE
     *
     * @return the value of u_code.SCODE
     *
     * @mbggenerated
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SCODE
     *
     * @param scode the value for u_code.SCODE
     *
     * @mbggenerated
     */
    public void setScode(String scode) {
        this.scode = scode == null ? null : scode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SNAME
     *
     * @return the value of u_code.SNAME
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SNAME
     *
     * @param sname the value for u_code.SNAME
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SDESCRIPTION
     *
     * @return the value of u_code.SDESCRIPTION
     *
     * @mbggenerated
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SDESCRIPTION
     *
     * @param sdescription the value for u_code.SDESCRIPTION
     *
     * @mbggenerated
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription == null ? null : sdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SREMARK
     *
     * @return the value of u_code.SREMARK
     *
     * @mbggenerated
     */
    public String getSremark() {
        return sremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SREMARK
     *
     * @param sremark the value for u_code.SREMARK
     *
     * @mbggenerated
     */
    public void setSremark(String sremark) {
        this.sremark = sremark == null ? null : sremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SCREATOR
     *
     * @return the value of u_code.SCREATOR
     *
     * @mbggenerated
     */
    public Long getScreator() {
        return screator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SCREATOR
     *
     * @param screator the value for u_code.SCREATOR
     *
     * @mbggenerated
     */
    public void setScreator(Long screator) {
        this.screator = screator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SCREATETIME
     *
     * @return the value of u_code.SCREATETIME
     *
     * @mbggenerated
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SCREATETIME
     *
     * @param screatetime the value for u_code.SCREATETIME
     *
     * @mbggenerated
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SMODIFIER
     *
     * @return the value of u_code.SMODIFIER
     *
     * @mbggenerated
     */
    public Long getSmodifier() {
        return smodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SMODIFIER
     *
     * @param smodifier the value for u_code.SMODIFIER
     *
     * @mbggenerated
     */
    public void setSmodifier(Long smodifier) {
        this.smodifier = smodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SMODIFYTIME
     *
     * @return the value of u_code.SMODIFYTIME
     *
     * @mbggenerated
     */
    public Date getSmodifytime() {
        return smodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SMODIFYTIME
     *
     * @param smodifytime the value for u_code.SMODIFYTIME
     *
     * @mbggenerated
     */
    public void setSmodifytime(Date smodifytime) {
        this.smodifytime = smodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.STYPE
     *
     * @return the value of u_code.STYPE
     *
     * @mbggenerated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.STYPE
     *
     * @param stype the value for u_code.STYPE
     *
     * @mbggenerated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SSTATE
     *
     * @return the value of u_code.SSTATE
     *
     * @mbggenerated
     */
    public Long getSstate() {
        return sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SSTATE
     *
     * @param sstate the value for u_code.SSTATE
     *
     * @mbggenerated
     */
    public void setSstate(Long sstate) {
        this.sstate = sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SLEVEL
     *
     * @return the value of u_code.SLEVEL
     *
     * @mbggenerated
     */
    public String getSlevel() {
        return slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SLEVEL
     *
     * @param slevel the value for u_code.SLEVEL
     *
     * @mbggenerated
     */
    public void setSlevel(String slevel) {
        this.slevel = slevel == null ? null : slevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SORDINAL
     *
     * @return the value of u_code.SORDINAL
     *
     * @mbggenerated
     */
    public String getSordinal() {
        return sordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SORDINAL
     *
     * @param sordinal the value for u_code.SORDINAL
     *
     * @mbggenerated
     */
    public void setSordinal(String sordinal) {
        this.sordinal = sordinal == null ? null : sordinal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SSYSTEM
     *
     * @return the value of u_code.SSYSTEM
     *
     * @mbggenerated
     */
    public String getSsystem() {
        return ssystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SSYSTEM
     *
     * @param ssystem the value for u_code.SSYSTEM
     *
     * @mbggenerated
     */
    public void setSsystem(String ssystem) {
        this.ssystem = ssystem == null ? null : ssystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SENABLED
     *
     * @return the value of u_code.SENABLED
     *
     * @mbggenerated
     */
    public String getSenabled() {
        return senabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SENABLED
     *
     * @param senabled the value for u_code.SENABLED
     *
     * @mbggenerated
     */
    public void setSenabled(String senabled) {
        this.senabled = senabled == null ? null : senabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.GPSADDRESS
     *
     * @return the value of u_code.GPSADDRESS
     *
     * @mbggenerated
     */
    public String getGpsaddress() {
        return gpsaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.GPSADDRESS
     *
     * @param gpsaddress the value for u_code.GPSADDRESS
     *
     * @mbggenerated
     */
    public void setGpsaddress(String gpsaddress) {
        this.gpsaddress = gpsaddress == null ? null : gpsaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.URLIMG
     *
     * @return the value of u_code.URLIMG
     *
     * @mbggenerated
     */
    public String getUrlimg() {
        return urlimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.URLIMG
     *
     * @param urlimg the value for u_code.URLIMG
     *
     * @mbggenerated
     */
    public void setUrlimg(String urlimg) {
        this.urlimg = urlimg == null ? null : urlimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.PARENTID
     *
     * @return the value of u_code.PARENTID
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.PARENTID
     *
     * @param parentid the value for u_code.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.CODETYPEID
     *
     * @return the value of u_code.CODETYPEID
     *
     * @mbggenerated
     */
    public Long getCodetypeid() {
        return codetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.CODETYPEID
     *
     * @param codetypeid the value for u_code.CODETYPEID
     *
     * @mbggenerated
     */
    public void setCodetypeid(Long codetypeid) {
        this.codetypeid = codetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.USERID
     *
     * @return the value of u_code.USERID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.USERID
     *
     * @param userid the value for u_code.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.GPSX
     *
     * @return the value of u_code.GPSX
     *
     * @mbggenerated
     */
    public BigDecimal getGpsx() {
        return gpsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.GPSX
     *
     * @param gpsx the value for u_code.GPSX
     *
     * @mbggenerated
     */
    public void setGpsx(BigDecimal gpsx) {
        this.gpsx = gpsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.GPSY
     *
     * @return the value of u_code.GPSY
     *
     * @mbggenerated
     */
    public BigDecimal getGpsy() {
        return gpsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.GPSY
     *
     * @param gpsy the value for u_code.GPSY
     *
     * @mbggenerated
     */
    public void setGpsy(BigDecimal gpsy) {
        this.gpsy = gpsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.SYEAR
     *
     * @return the value of u_code.SYEAR
     *
     * @mbggenerated
     */
    public String getSyear() {
        return syear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.SYEAR
     *
     * @param syear the value for u_code.SYEAR
     *
     * @mbggenerated
     */
    public void setSyear(String syear) {
        this.syear = syear == null ? null : syear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.UFCODE
     *
     * @return the value of u_code.UFCODE
     *
     * @mbggenerated
     */
    public String getUfcode() {
        return ufcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.UFCODE
     *
     * @param ufcode the value for u_code.UFCODE
     *
     * @mbggenerated
     */
    public void setUfcode(String ufcode) {
        this.ufcode = ufcode == null ? null : ufcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.HOUSEID
     *
     * @return the value of u_code.HOUSEID
     *
     * @mbggenerated
     */
    public Integer getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.HOUSEID
     *
     * @param houseid the value for u_code.HOUSEID
     *
     * @mbggenerated
     */
    public void setHouseid(Integer houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.PACKAGEID
     *
     * @return the value of u_code.PACKAGEID
     *
     * @mbggenerated
     */
    public Long getPackageid() {
        return packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.PACKAGEID
     *
     * @param packageid the value for u_code.PACKAGEID
     *
     * @mbggenerated
     */
    public void setPackageid(Long packageid) {
        this.packageid = packageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.ELEVATORID
     *
     * @return the value of u_code.ELEVATORID
     *
     * @mbggenerated
     */
    public Long getElevatorid() {
        return elevatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.ELEVATORID
     *
     * @param elevatorid the value for u_code.ELEVATORID
     *
     * @mbggenerated
     */
    public void setElevatorid(Long elevatorid) {
        this.elevatorid = elevatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.REGCODE
     *
     * @return the value of u_code.REGCODE
     *
     * @mbggenerated
     */
    public String getRegcode() {
        return regcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.REGCODE
     *
     * @param regcode the value for u_code.REGCODE
     *
     * @mbggenerated
     */
    public void setRegcode(String regcode) {
        this.regcode = regcode == null ? null : regcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_code.TEXTCONTENT
     *
     * @return the value of u_code.TEXTCONTENT
     *
     * @mbggenerated
     */
    public String getTextcontent() {
        return textcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_code.TEXTCONTENT
     *
     * @param textcontent the value for u_code.TEXTCONTENT
     *
     * @mbggenerated
     */
    public void setTextcontent(String textcontent) {
        this.textcontent = textcontent == null ? null : textcontent.trim();
    }
}