package com.jorchi.elevator.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class codeElevatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public codeElevatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andScodeIsNull() {
            addCriterion("SCODE is null");
            return (Criteria) this;
        }

        public Criteria andScodeIsNotNull() {
            addCriterion("SCODE is not null");
            return (Criteria) this;
        }

        public Criteria andScodeEqualTo(String value) {
            addCriterion("SCODE =", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotEqualTo(String value) {
            addCriterion("SCODE <>", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeGreaterThan(String value) {
            addCriterion("SCODE >", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeGreaterThanOrEqualTo(String value) {
            addCriterion("SCODE >=", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLessThan(String value) {
            addCriterion("SCODE <", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLessThanOrEqualTo(String value) {
            addCriterion("SCODE <=", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLike(String value) {
            addCriterion("SCODE like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotLike(String value) {
            addCriterion("SCODE not like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeIn(List<String> values) {
            addCriterion("SCODE in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotIn(List<String> values) {
            addCriterion("SCODE not in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeBetween(String value1, String value2) {
            addCriterion("SCODE between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotBetween(String value1, String value2) {
            addCriterion("SCODE not between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andSnameIsNull() {
            addCriterion("SNAME is null");
            return (Criteria) this;
        }

        public Criteria andSnameIsNotNull() {
            addCriterion("SNAME is not null");
            return (Criteria) this;
        }

        public Criteria andSnameEqualTo(String value) {
            addCriterion("SNAME =", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotEqualTo(String value) {
            addCriterion("SNAME <>", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThan(String value) {
            addCriterion("SNAME >", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThanOrEqualTo(String value) {
            addCriterion("SNAME >=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThan(String value) {
            addCriterion("SNAME <", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThanOrEqualTo(String value) {
            addCriterion("SNAME <=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLike(String value) {
            addCriterion("SNAME like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotLike(String value) {
            addCriterion("SNAME not like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameIn(List<String> values) {
            addCriterion("SNAME in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotIn(List<String> values) {
            addCriterion("SNAME not in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameBetween(String value1, String value2) {
            addCriterion("SNAME between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotBetween(String value1, String value2) {
            addCriterion("SNAME not between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNull() {
            addCriterion("SREMARK is null");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNotNull() {
            addCriterion("SREMARK is not null");
            return (Criteria) this;
        }

        public Criteria andSremarkEqualTo(String value) {
            addCriterion("SREMARK =", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotEqualTo(String value) {
            addCriterion("SREMARK <>", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkGreaterThan(String value) {
            addCriterion("SREMARK >", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkGreaterThanOrEqualTo(String value) {
            addCriterion("SREMARK >=", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLessThan(String value) {
            addCriterion("SREMARK <", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLessThanOrEqualTo(String value) {
            addCriterion("SREMARK <=", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLike(String value) {
            addCriterion("SREMARK like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotLike(String value) {
            addCriterion("SREMARK not like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkIn(List<String> values) {
            addCriterion("SREMARK in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotIn(List<String> values) {
            addCriterion("SREMARK not in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkBetween(String value1, String value2) {
            addCriterion("SREMARK between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotBetween(String value1, String value2) {
            addCriterion("SREMARK not between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andScreatorIsNull() {
            addCriterion("SCREATOR is null");
            return (Criteria) this;
        }

        public Criteria andScreatorIsNotNull() {
            addCriterion("SCREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andScreatorEqualTo(Long value) {
            addCriterion("SCREATOR =", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotEqualTo(Long value) {
            addCriterion("SCREATOR <>", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorGreaterThan(Long value) {
            addCriterion("SCREATOR >", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("SCREATOR >=", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorLessThan(Long value) {
            addCriterion("SCREATOR <", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorLessThanOrEqualTo(Long value) {
            addCriterion("SCREATOR <=", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorIn(List<Long> values) {
            addCriterion("SCREATOR in", values, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotIn(List<Long> values) {
            addCriterion("SCREATOR not in", values, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorBetween(Long value1, Long value2) {
            addCriterion("SCREATOR between", value1, value2, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotBetween(Long value1, Long value2) {
            addCriterion("SCREATOR not between", value1, value2, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIsNull() {
            addCriterion("SCREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIsNotNull() {
            addCriterion("SCREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andScreatetimeEqualTo(Date value) {
            addCriterion("SCREATETIME =", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotEqualTo(Date value) {
            addCriterion("SCREATETIME <>", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeGreaterThan(Date value) {
            addCriterion("SCREATETIME >", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCREATETIME >=", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeLessThan(Date value) {
            addCriterion("SCREATETIME <", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("SCREATETIME <=", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIn(List<Date> values) {
            addCriterion("SCREATETIME in", values, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotIn(List<Date> values) {
            addCriterion("SCREATETIME not in", values, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeBetween(Date value1, Date value2) {
            addCriterion("SCREATETIME between", value1, value2, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("SCREATETIME not between", value1, value2, "screatetime");
            return (Criteria) this;
        }

        public Criteria andSmodifierIsNull() {
            addCriterion("SMODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andSmodifierIsNotNull() {
            addCriterion("SMODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andSmodifierEqualTo(Long value) {
            addCriterion("SMODIFIER =", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotEqualTo(Long value) {
            addCriterion("SMODIFIER <>", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierGreaterThan(Long value) {
            addCriterion("SMODIFIER >", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierGreaterThanOrEqualTo(Long value) {
            addCriterion("SMODIFIER >=", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierLessThan(Long value) {
            addCriterion("SMODIFIER <", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierLessThanOrEqualTo(Long value) {
            addCriterion("SMODIFIER <=", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierIn(List<Long> values) {
            addCriterion("SMODIFIER in", values, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotIn(List<Long> values) {
            addCriterion("SMODIFIER not in", values, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierBetween(Long value1, Long value2) {
            addCriterion("SMODIFIER between", value1, value2, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotBetween(Long value1, Long value2) {
            addCriterion("SMODIFIER not between", value1, value2, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIsNull() {
            addCriterion("SMODIFYTIME is null");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIsNotNull() {
            addCriterion("SMODIFYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeEqualTo(Date value) {
            addCriterion("SMODIFYTIME =", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotEqualTo(Date value) {
            addCriterion("SMODIFYTIME <>", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeGreaterThan(Date value) {
            addCriterion("SMODIFYTIME >", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMODIFYTIME >=", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeLessThan(Date value) {
            addCriterion("SMODIFYTIME <", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeLessThanOrEqualTo(Date value) {
            addCriterion("SMODIFYTIME <=", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIn(List<Date> values) {
            addCriterion("SMODIFYTIME in", values, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotIn(List<Date> values) {
            addCriterion("SMODIFYTIME not in", values, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeBetween(Date value1, Date value2) {
            addCriterion("SMODIFYTIME between", value1, value2, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotBetween(Date value1, Date value2) {
            addCriterion("SMODIFYTIME not between", value1, value2, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andStypeIsNull() {
            addCriterion("STYPE is null");
            return (Criteria) this;
        }

        public Criteria andStypeIsNotNull() {
            addCriterion("STYPE is not null");
            return (Criteria) this;
        }

        public Criteria andStypeEqualTo(String value) {
            addCriterion("STYPE =", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotEqualTo(String value) {
            addCriterion("STYPE <>", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThan(String value) {
            addCriterion("STYPE >", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThanOrEqualTo(String value) {
            addCriterion("STYPE >=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThan(String value) {
            addCriterion("STYPE <", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThanOrEqualTo(String value) {
            addCriterion("STYPE <=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLike(String value) {
            addCriterion("STYPE like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotLike(String value) {
            addCriterion("STYPE not like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeIn(List<String> values) {
            addCriterion("STYPE in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotIn(List<String> values) {
            addCriterion("STYPE not in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeBetween(String value1, String value2) {
            addCriterion("STYPE between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotBetween(String value1, String value2) {
            addCriterion("STYPE not between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andSsystemIsNull() {
            addCriterion("SSYSTEM is null");
            return (Criteria) this;
        }

        public Criteria andSsystemIsNotNull() {
            addCriterion("SSYSTEM is not null");
            return (Criteria) this;
        }

        public Criteria andSsystemEqualTo(String value) {
            addCriterion("SSYSTEM =", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotEqualTo(String value) {
            addCriterion("SSYSTEM <>", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemGreaterThan(String value) {
            addCriterion("SSYSTEM >", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemGreaterThanOrEqualTo(String value) {
            addCriterion("SSYSTEM >=", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLessThan(String value) {
            addCriterion("SSYSTEM <", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLessThanOrEqualTo(String value) {
            addCriterion("SSYSTEM <=", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLike(String value) {
            addCriterion("SSYSTEM like", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotLike(String value) {
            addCriterion("SSYSTEM not like", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemIn(List<String> values) {
            addCriterion("SSYSTEM in", values, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotIn(List<String> values) {
            addCriterion("SSYSTEM not in", values, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemBetween(String value1, String value2) {
            addCriterion("SSYSTEM between", value1, value2, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotBetween(String value1, String value2) {
            addCriterion("SSYSTEM not between", value1, value2, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSenabledIsNull() {
            addCriterion("SENABLED is null");
            return (Criteria) this;
        }

        public Criteria andSenabledIsNotNull() {
            addCriterion("SENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andSenabledEqualTo(String value) {
            addCriterion("SENABLED =", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotEqualTo(String value) {
            addCriterion("SENABLED <>", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledGreaterThan(String value) {
            addCriterion("SENABLED >", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledGreaterThanOrEqualTo(String value) {
            addCriterion("SENABLED >=", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLessThan(String value) {
            addCriterion("SENABLED <", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLessThanOrEqualTo(String value) {
            addCriterion("SENABLED <=", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLike(String value) {
            addCriterion("SENABLED like", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotLike(String value) {
            addCriterion("SENABLED not like", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledIn(List<String> values) {
            addCriterion("SENABLED in", values, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotIn(List<String> values) {
            addCriterion("SENABLED not in", values, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledBetween(String value1, String value2) {
            addCriterion("SENABLED between", value1, value2, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotBetween(String value1, String value2) {
            addCriterion("SENABLED not between", value1, value2, "senabled");
            return (Criteria) this;
        }

        public Criteria andSstateIsNull() {
            addCriterion("SSTATE is null");
            return (Criteria) this;
        }

        public Criteria andSstateIsNotNull() {
            addCriterion("SSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andSstateEqualTo(Long value) {
            addCriterion("SSTATE =", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotEqualTo(Long value) {
            addCriterion("SSTATE <>", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateGreaterThan(Long value) {
            addCriterion("SSTATE >", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateGreaterThanOrEqualTo(Long value) {
            addCriterion("SSTATE >=", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateLessThan(Long value) {
            addCriterion("SSTATE <", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateLessThanOrEqualTo(Long value) {
            addCriterion("SSTATE <=", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateIn(List<Long> values) {
            addCriterion("SSTATE in", values, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotIn(List<Long> values) {
            addCriterion("SSTATE not in", values, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateBetween(Long value1, Long value2) {
            addCriterion("SSTATE between", value1, value2, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotBetween(Long value1, Long value2) {
            addCriterion("SSTATE not between", value1, value2, "sstate");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNull() {
            addCriterion("SLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNotNull() {
            addCriterion("SLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSlevelEqualTo(String value) {
            addCriterion("SLEVEL =", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotEqualTo(String value) {
            addCriterion("SLEVEL <>", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThan(String value) {
            addCriterion("SLEVEL >", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThanOrEqualTo(String value) {
            addCriterion("SLEVEL >=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThan(String value) {
            addCriterion("SLEVEL <", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThanOrEqualTo(String value) {
            addCriterion("SLEVEL <=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLike(String value) {
            addCriterion("SLEVEL like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotLike(String value) {
            addCriterion("SLEVEL not like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelIn(List<String> values) {
            addCriterion("SLEVEL in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotIn(List<String> values) {
            addCriterion("SLEVEL not in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelBetween(String value1, String value2) {
            addCriterion("SLEVEL between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotBetween(String value1, String value2) {
            addCriterion("SLEVEL not between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSordinalIsNull() {
            addCriterion("SORDINAL is null");
            return (Criteria) this;
        }

        public Criteria andSordinalIsNotNull() {
            addCriterion("SORDINAL is not null");
            return (Criteria) this;
        }

        public Criteria andSordinalEqualTo(String value) {
            addCriterion("SORDINAL =", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotEqualTo(String value) {
            addCriterion("SORDINAL <>", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalGreaterThan(String value) {
            addCriterion("SORDINAL >", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalGreaterThanOrEqualTo(String value) {
            addCriterion("SORDINAL >=", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLessThan(String value) {
            addCriterion("SORDINAL <", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLessThanOrEqualTo(String value) {
            addCriterion("SORDINAL <=", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLike(String value) {
            addCriterion("SORDINAL like", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotLike(String value) {
            addCriterion("SORDINAL not like", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalIn(List<String> values) {
            addCriterion("SORDINAL in", values, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotIn(List<String> values) {
            addCriterion("SORDINAL not in", values, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalBetween(String value1, String value2) {
            addCriterion("SORDINAL between", value1, value2, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotBetween(String value1, String value2) {
            addCriterion("SORDINAL not between", value1, value2, "sordinal");
            return (Criteria) this;
        }

        public Criteria andPropertycompIsNull() {
            addCriterion("PROPERTYCOMP is null");
            return (Criteria) this;
        }

        public Criteria andPropertycompIsNotNull() {
            addCriterion("PROPERTYCOMP is not null");
            return (Criteria) this;
        }

        public Criteria andPropertycompEqualTo(String value) {
            addCriterion("PROPERTYCOMP =", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompNotEqualTo(String value) {
            addCriterion("PROPERTYCOMP <>", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompGreaterThan(String value) {
            addCriterion("PROPERTYCOMP >", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYCOMP >=", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompLessThan(String value) {
            addCriterion("PROPERTYCOMP <", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYCOMP <=", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompLike(String value) {
            addCriterion("PROPERTYCOMP like", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompNotLike(String value) {
            addCriterion("PROPERTYCOMP not like", value, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompIn(List<String> values) {
            addCriterion("PROPERTYCOMP in", values, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompNotIn(List<String> values) {
            addCriterion("PROPERTYCOMP not in", values, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompBetween(String value1, String value2) {
            addCriterion("PROPERTYCOMP between", value1, value2, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andPropertycompNotBetween(String value1, String value2) {
            addCriterion("PROPERTYCOMP not between", value1, value2, "propertycomp");
            return (Criteria) this;
        }

        public Criteria andVillagenameIsNull() {
            addCriterion("VILLAGENAME is null");
            return (Criteria) this;
        }

        public Criteria andVillagenameIsNotNull() {
            addCriterion("VILLAGENAME is not null");
            return (Criteria) this;
        }

        public Criteria andVillagenameEqualTo(String value) {
            addCriterion("VILLAGENAME =", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameNotEqualTo(String value) {
            addCriterion("VILLAGENAME <>", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameGreaterThan(String value) {
            addCriterion("VILLAGENAME >", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameGreaterThanOrEqualTo(String value) {
            addCriterion("VILLAGENAME >=", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameLessThan(String value) {
            addCriterion("VILLAGENAME <", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameLessThanOrEqualTo(String value) {
            addCriterion("VILLAGENAME <=", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameLike(String value) {
            addCriterion("VILLAGENAME like", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameNotLike(String value) {
            addCriterion("VILLAGENAME not like", value, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameIn(List<String> values) {
            addCriterion("VILLAGENAME in", values, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameNotIn(List<String> values) {
            addCriterion("VILLAGENAME not in", values, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameBetween(String value1, String value2) {
            addCriterion("VILLAGENAME between", value1, value2, "villagename");
            return (Criteria) this;
        }

        public Criteria andVillagenameNotBetween(String value1, String value2) {
            addCriterion("VILLAGENAME not between", value1, value2, "villagename");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandIsNull() {
            addCriterion("ELEVATORBRAND is null");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandIsNotNull() {
            addCriterion("ELEVATORBRAND is not null");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandEqualTo(String value) {
            addCriterion("ELEVATORBRAND =", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandNotEqualTo(String value) {
            addCriterion("ELEVATORBRAND <>", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandGreaterThan(String value) {
            addCriterion("ELEVATORBRAND >", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandGreaterThanOrEqualTo(String value) {
            addCriterion("ELEVATORBRAND >=", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandLessThan(String value) {
            addCriterion("ELEVATORBRAND <", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandLessThanOrEqualTo(String value) {
            addCriterion("ELEVATORBRAND <=", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandLike(String value) {
            addCriterion("ELEVATORBRAND like", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandNotLike(String value) {
            addCriterion("ELEVATORBRAND not like", value, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandIn(List<String> values) {
            addCriterion("ELEVATORBRAND in", values, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandNotIn(List<String> values) {
            addCriterion("ELEVATORBRAND not in", values, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandBetween(String value1, String value2) {
            addCriterion("ELEVATORBRAND between", value1, value2, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatorbrandNotBetween(String value1, String value2) {
            addCriterion("ELEVATORBRAND not between", value1, value2, "elevatorbrand");
            return (Criteria) this;
        }

        public Criteria andElevatormodelIsNull() {
            addCriterion("ELEVATORMODEL is null");
            return (Criteria) this;
        }

        public Criteria andElevatormodelIsNotNull() {
            addCriterion("ELEVATORMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andElevatormodelEqualTo(String value) {
            addCriterion("ELEVATORMODEL =", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelNotEqualTo(String value) {
            addCriterion("ELEVATORMODEL <>", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelGreaterThan(String value) {
            addCriterion("ELEVATORMODEL >", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelGreaterThanOrEqualTo(String value) {
            addCriterion("ELEVATORMODEL >=", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelLessThan(String value) {
            addCriterion("ELEVATORMODEL <", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelLessThanOrEqualTo(String value) {
            addCriterion("ELEVATORMODEL <=", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelLike(String value) {
            addCriterion("ELEVATORMODEL like", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelNotLike(String value) {
            addCriterion("ELEVATORMODEL not like", value, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelIn(List<String> values) {
            addCriterion("ELEVATORMODEL in", values, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelNotIn(List<String> values) {
            addCriterion("ELEVATORMODEL not in", values, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelBetween(String value1, String value2) {
            addCriterion("ELEVATORMODEL between", value1, value2, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andElevatormodelNotBetween(String value1, String value2) {
            addCriterion("ELEVATORMODEL not between", value1, value2, "elevatormodel");
            return (Criteria) this;
        }

        public Criteria andLoadweightIsNull() {
            addCriterion("LOADWEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andLoadweightIsNotNull() {
            addCriterion("LOADWEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andLoadweightEqualTo(String value) {
            addCriterion("LOADWEIGHT =", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightNotEqualTo(String value) {
            addCriterion("LOADWEIGHT <>", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightGreaterThan(String value) {
            addCriterion("LOADWEIGHT >", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightGreaterThanOrEqualTo(String value) {
            addCriterion("LOADWEIGHT >=", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightLessThan(String value) {
            addCriterion("LOADWEIGHT <", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightLessThanOrEqualTo(String value) {
            addCriterion("LOADWEIGHT <=", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightLike(String value) {
            addCriterion("LOADWEIGHT like", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightNotLike(String value) {
            addCriterion("LOADWEIGHT not like", value, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightIn(List<String> values) {
            addCriterion("LOADWEIGHT in", values, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightNotIn(List<String> values) {
            addCriterion("LOADWEIGHT not in", values, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightBetween(String value1, String value2) {
            addCriterion("LOADWEIGHT between", value1, value2, "loadweight");
            return (Criteria) this;
        }

        public Criteria andLoadweightNotBetween(String value1, String value2) {
            addCriterion("LOADWEIGHT not between", value1, value2, "loadweight");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNull() {
            addCriterion("SPEED is null");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNotNull() {
            addCriterion("SPEED is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedEqualTo(String value) {
            addCriterion("SPEED =", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotEqualTo(String value) {
            addCriterion("SPEED <>", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThan(String value) {
            addCriterion("SPEED >", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThanOrEqualTo(String value) {
            addCriterion("SPEED >=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThan(String value) {
            addCriterion("SPEED <", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThanOrEqualTo(String value) {
            addCriterion("SPEED <=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLike(String value) {
            addCriterion("SPEED like", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotLike(String value) {
            addCriterion("SPEED not like", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedIn(List<String> values) {
            addCriterion("SPEED in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotIn(List<String> values) {
            addCriterion("SPEED not in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedBetween(String value1, String value2) {
            addCriterion("SPEED between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotBetween(String value1, String value2) {
            addCriterion("SPEED not between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andLayernumberIsNull() {
            addCriterion("LAYERNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andLayernumberIsNotNull() {
            addCriterion("LAYERNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andLayernumberEqualTo(String value) {
            addCriterion("LAYERNUMBER =", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberNotEqualTo(String value) {
            addCriterion("LAYERNUMBER <>", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberGreaterThan(String value) {
            addCriterion("LAYERNUMBER >", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberGreaterThanOrEqualTo(String value) {
            addCriterion("LAYERNUMBER >=", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberLessThan(String value) {
            addCriterion("LAYERNUMBER <", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberLessThanOrEqualTo(String value) {
            addCriterion("LAYERNUMBER <=", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberLike(String value) {
            addCriterion("LAYERNUMBER like", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberNotLike(String value) {
            addCriterion("LAYERNUMBER not like", value, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberIn(List<String> values) {
            addCriterion("LAYERNUMBER in", values, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberNotIn(List<String> values) {
            addCriterion("LAYERNUMBER not in", values, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberBetween(String value1, String value2) {
            addCriterion("LAYERNUMBER between", value1, value2, "layernumber");
            return (Criteria) this;
        }

        public Criteria andLayernumberNotBetween(String value1, String value2) {
            addCriterion("LAYERNUMBER not between", value1, value2, "layernumber");
            return (Criteria) this;
        }

        public Criteria andDeliverdateIsNull() {
            addCriterion("DELIVERDATE is null");
            return (Criteria) this;
        }

        public Criteria andDeliverdateIsNotNull() {
            addCriterion("DELIVERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverdateEqualTo(Date value) {
            addCriterion("DELIVERDATE =", value, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateNotEqualTo(Date value) {
            addCriterion("DELIVERDATE <>", value, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateGreaterThan(Date value) {
            addCriterion("DELIVERDATE >", value, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateGreaterThanOrEqualTo(Date value) {
            addCriterion("DELIVERDATE >=", value, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateLessThan(Date value) {
            addCriterion("DELIVERDATE <", value, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateLessThanOrEqualTo(Date value) {
            addCriterion("DELIVERDATE <=", value, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateIn(List<Date> values) {
            addCriterion("DELIVERDATE in", values, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateNotIn(List<Date> values) {
            addCriterion("DELIVERDATE not in", values, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateBetween(Date value1, Date value2) {
            addCriterion("DELIVERDATE between", value1, value2, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andDeliverdateNotBetween(Date value1, Date value2) {
            addCriterion("DELIVERDATE not between", value1, value2, "deliverdate");
            return (Criteria) this;
        }

        public Criteria andOccasionIsNull() {
            addCriterion("OCCASION is null");
            return (Criteria) this;
        }

        public Criteria andOccasionIsNotNull() {
            addCriterion("OCCASION is not null");
            return (Criteria) this;
        }

        public Criteria andOccasionEqualTo(String value) {
            addCriterion("OCCASION =", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionNotEqualTo(String value) {
            addCriterion("OCCASION <>", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionGreaterThan(String value) {
            addCriterion("OCCASION >", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionGreaterThanOrEqualTo(String value) {
            addCriterion("OCCASION >=", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionLessThan(String value) {
            addCriterion("OCCASION <", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionLessThanOrEqualTo(String value) {
            addCriterion("OCCASION <=", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionLike(String value) {
            addCriterion("OCCASION like", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionNotLike(String value) {
            addCriterion("OCCASION not like", value, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionIn(List<String> values) {
            addCriterion("OCCASION in", values, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionNotIn(List<String> values) {
            addCriterion("OCCASION not in", values, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionBetween(String value1, String value2) {
            addCriterion("OCCASION between", value1, value2, "occasion");
            return (Criteria) this;
        }

        public Criteria andOccasionNotBetween(String value1, String value2) {
            addCriterion("OCCASION not between", value1, value2, "occasion");
            return (Criteria) this;
        }

        public Criteria andInspectiondateIsNull() {
            addCriterion("INSPECTIONDATE is null");
            return (Criteria) this;
        }

        public Criteria andInspectiondateIsNotNull() {
            addCriterion("INSPECTIONDATE is not null");
            return (Criteria) this;
        }

        public Criteria andInspectiondateEqualTo(Date value) {
            addCriterion("INSPECTIONDATE =", value, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateNotEqualTo(Date value) {
            addCriterion("INSPECTIONDATE <>", value, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateGreaterThan(Date value) {
            addCriterion("INSPECTIONDATE >", value, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateGreaterThanOrEqualTo(Date value) {
            addCriterion("INSPECTIONDATE >=", value, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateLessThan(Date value) {
            addCriterion("INSPECTIONDATE <", value, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateLessThanOrEqualTo(Date value) {
            addCriterion("INSPECTIONDATE <=", value, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateIn(List<Date> values) {
            addCriterion("INSPECTIONDATE in", values, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateNotIn(List<Date> values) {
            addCriterion("INSPECTIONDATE not in", values, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateBetween(Date value1, Date value2) {
            addCriterion("INSPECTIONDATE between", value1, value2, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andInspectiondateNotBetween(Date value1, Date value2) {
            addCriterion("INSPECTIONDATE not between", value1, value2, "inspectiondate");
            return (Criteria) this;
        }

        public Criteria andImportornotIsNull() {
            addCriterion("IMPORTORNOT is null");
            return (Criteria) this;
        }

        public Criteria andImportornotIsNotNull() {
            addCriterion("IMPORTORNOT is not null");
            return (Criteria) this;
        }

        public Criteria andImportornotEqualTo(String value) {
            addCriterion("IMPORTORNOT =", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotNotEqualTo(String value) {
            addCriterion("IMPORTORNOT <>", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotGreaterThan(String value) {
            addCriterion("IMPORTORNOT >", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotGreaterThanOrEqualTo(String value) {
            addCriterion("IMPORTORNOT >=", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotLessThan(String value) {
            addCriterion("IMPORTORNOT <", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotLessThanOrEqualTo(String value) {
            addCriterion("IMPORTORNOT <=", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotLike(String value) {
            addCriterion("IMPORTORNOT like", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotNotLike(String value) {
            addCriterion("IMPORTORNOT not like", value, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotIn(List<String> values) {
            addCriterion("IMPORTORNOT in", values, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotNotIn(List<String> values) {
            addCriterion("IMPORTORNOT not in", values, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotBetween(String value1, String value2) {
            addCriterion("IMPORTORNOT between", value1, value2, "importornot");
            return (Criteria) this;
        }

        public Criteria andImportornotNotBetween(String value1, String value2) {
            addCriterion("IMPORTORNOT not between", value1, value2, "importornot");
            return (Criteria) this;
        }

        public Criteria andProductionnumberIsNull() {
            addCriterion("PRODUCTIONNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andProductionnumberIsNotNull() {
            addCriterion("PRODUCTIONNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andProductionnumberEqualTo(String value) {
            addCriterion("PRODUCTIONNUMBER =", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberNotEqualTo(String value) {
            addCriterion("PRODUCTIONNUMBER <>", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberGreaterThan(String value) {
            addCriterion("PRODUCTIONNUMBER >", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTIONNUMBER >=", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberLessThan(String value) {
            addCriterion("PRODUCTIONNUMBER <", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTIONNUMBER <=", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberLike(String value) {
            addCriterion("PRODUCTIONNUMBER like", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberNotLike(String value) {
            addCriterion("PRODUCTIONNUMBER not like", value, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberIn(List<String> values) {
            addCriterion("PRODUCTIONNUMBER in", values, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberNotIn(List<String> values) {
            addCriterion("PRODUCTIONNUMBER not in", values, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberBetween(String value1, String value2) {
            addCriterion("PRODUCTIONNUMBER between", value1, value2, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andProductionnumberNotBetween(String value1, String value2) {
            addCriterion("PRODUCTIONNUMBER not between", value1, value2, "productionnumber");
            return (Criteria) this;
        }

        public Criteria andComputerroomIsNull() {
            addCriterion("COMPUTERROOM is null");
            return (Criteria) this;
        }

        public Criteria andComputerroomIsNotNull() {
            addCriterion("COMPUTERROOM is not null");
            return (Criteria) this;
        }

        public Criteria andComputerroomEqualTo(String value) {
            addCriterion("COMPUTERROOM =", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomNotEqualTo(String value) {
            addCriterion("COMPUTERROOM <>", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomGreaterThan(String value) {
            addCriterion("COMPUTERROOM >", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomGreaterThanOrEqualTo(String value) {
            addCriterion("COMPUTERROOM >=", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomLessThan(String value) {
            addCriterion("COMPUTERROOM <", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomLessThanOrEqualTo(String value) {
            addCriterion("COMPUTERROOM <=", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomLike(String value) {
            addCriterion("COMPUTERROOM like", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomNotLike(String value) {
            addCriterion("COMPUTERROOM not like", value, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomIn(List<String> values) {
            addCriterion("COMPUTERROOM in", values, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomNotIn(List<String> values) {
            addCriterion("COMPUTERROOM not in", values, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomBetween(String value1, String value2) {
            addCriterion("COMPUTERROOM between", value1, value2, "computerroom");
            return (Criteria) this;
        }

        public Criteria andComputerroomNotBetween(String value1, String value2) {
            addCriterion("COMPUTERROOM not between", value1, value2, "computerroom");
            return (Criteria) this;
        }

        public Criteria andElevatortypeIsNull() {
            addCriterion("ELEVATORTYPE is null");
            return (Criteria) this;
        }

        public Criteria andElevatortypeIsNotNull() {
            addCriterion("ELEVATORTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andElevatortypeEqualTo(String value) {
            addCriterion("ELEVATORTYPE =", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeNotEqualTo(String value) {
            addCriterion("ELEVATORTYPE <>", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeGreaterThan(String value) {
            addCriterion("ELEVATORTYPE >", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeGreaterThanOrEqualTo(String value) {
            addCriterion("ELEVATORTYPE >=", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeLessThan(String value) {
            addCriterion("ELEVATORTYPE <", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeLessThanOrEqualTo(String value) {
            addCriterion("ELEVATORTYPE <=", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeLike(String value) {
            addCriterion("ELEVATORTYPE like", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeNotLike(String value) {
            addCriterion("ELEVATORTYPE not like", value, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeIn(List<String> values) {
            addCriterion("ELEVATORTYPE in", values, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeNotIn(List<String> values) {
            addCriterion("ELEVATORTYPE not in", values, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeBetween(String value1, String value2) {
            addCriterion("ELEVATORTYPE between", value1, value2, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andElevatortypeNotBetween(String value1, String value2) {
            addCriterion("ELEVATORTYPE not between", value1, value2, "elevatortype");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("CATEGORY =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("CATEGORY <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("CATEGORY >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("CATEGORY <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("CATEGORY like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("CATEGORY not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("CATEGORY in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("CATEGORY not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("CATEGORY between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("CATEGORY not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpIsNull() {
            addCriterion("SPECIALPURP is null");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpIsNotNull() {
            addCriterion("SPECIALPURP is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpEqualTo(String value) {
            addCriterion("SPECIALPURP =", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpNotEqualTo(String value) {
            addCriterion("SPECIALPURP <>", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpGreaterThan(String value) {
            addCriterion("SPECIALPURP >", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpGreaterThanOrEqualTo(String value) {
            addCriterion("SPECIALPURP >=", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpLessThan(String value) {
            addCriterion("SPECIALPURP <", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpLessThanOrEqualTo(String value) {
            addCriterion("SPECIALPURP <=", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpLike(String value) {
            addCriterion("SPECIALPURP like", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpNotLike(String value) {
            addCriterion("SPECIALPURP not like", value, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpIn(List<String> values) {
            addCriterion("SPECIALPURP in", values, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpNotIn(List<String> values) {
            addCriterion("SPECIALPURP not in", values, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpBetween(String value1, String value2) {
            addCriterion("SPECIALPURP between", value1, value2, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andSpecialpurpNotBetween(String value1, String value2) {
            addCriterion("SPECIALPURP not between", value1, value2, "specialpurp");
            return (Criteria) this;
        }

        public Criteria andCodeidIsNull() {
            addCriterion("CODEID is null");
            return (Criteria) this;
        }

        public Criteria andCodeidIsNotNull() {
            addCriterion("CODEID is not null");
            return (Criteria) this;
        }

        public Criteria andCodeidEqualTo(Integer value) {
            addCriterion("CODEID =", value, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidNotEqualTo(Integer value) {
            addCriterion("CODEID <>", value, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidGreaterThan(Integer value) {
            addCriterion("CODEID >", value, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CODEID >=", value, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidLessThan(Integer value) {
            addCriterion("CODEID <", value, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidLessThanOrEqualTo(Integer value) {
            addCriterion("CODEID <=", value, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidIn(List<Integer> values) {
            addCriterion("CODEID in", values, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidNotIn(List<Integer> values) {
            addCriterion("CODEID not in", values, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidBetween(Integer value1, Integer value2) {
            addCriterion("CODEID between", value1, value2, "codeid");
            return (Criteria) this;
        }

        public Criteria andCodeidNotBetween(Integer value1, Integer value2) {
            addCriterion("CODEID not between", value1, value2, "codeid");
            return (Criteria) this;
        }

        public Criteria andSeedidIsNull() {
            addCriterion("SEEDID is null");
            return (Criteria) this;
        }

        public Criteria andSeedidIsNotNull() {
            addCriterion("SEEDID is not null");
            return (Criteria) this;
        }

        public Criteria andSeedidEqualTo(String value) {
            addCriterion("SEEDID =", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidNotEqualTo(String value) {
            addCriterion("SEEDID <>", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidGreaterThan(String value) {
            addCriterion("SEEDID >", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidGreaterThanOrEqualTo(String value) {
            addCriterion("SEEDID >=", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidLessThan(String value) {
            addCriterion("SEEDID <", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidLessThanOrEqualTo(String value) {
            addCriterion("SEEDID <=", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidLike(String value) {
            addCriterion("SEEDID like", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidNotLike(String value) {
            addCriterion("SEEDID not like", value, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidIn(List<String> values) {
            addCriterion("SEEDID in", values, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidNotIn(List<String> values) {
            addCriterion("SEEDID not in", values, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidBetween(String value1, String value2) {
            addCriterion("SEEDID between", value1, value2, "seedid");
            return (Criteria) this;
        }

        public Criteria andSeedidNotBetween(String value1, String value2) {
            addCriterion("SEEDID not between", value1, value2, "seedid");
            return (Criteria) this;
        }

        public Criteria andIsneedIsNull() {
            addCriterion("ISNEED is null");
            return (Criteria) this;
        }

        public Criteria andIsneedIsNotNull() {
            addCriterion("ISNEED is not null");
            return (Criteria) this;
        }

        public Criteria andIsneedEqualTo(String value) {
            addCriterion("ISNEED =", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedNotEqualTo(String value) {
            addCriterion("ISNEED <>", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedGreaterThan(String value) {
            addCriterion("ISNEED >", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedGreaterThanOrEqualTo(String value) {
            addCriterion("ISNEED >=", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedLessThan(String value) {
            addCriterion("ISNEED <", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedLessThanOrEqualTo(String value) {
            addCriterion("ISNEED <=", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedLike(String value) {
            addCriterion("ISNEED like", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedNotLike(String value) {
            addCriterion("ISNEED not like", value, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedIn(List<String> values) {
            addCriterion("ISNEED in", values, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedNotIn(List<String> values) {
            addCriterion("ISNEED not in", values, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedBetween(String value1, String value2) {
            addCriterion("ISNEED between", value1, value2, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsneedNotBetween(String value1, String value2) {
            addCriterion("ISNEED not between", value1, value2, "isneed");
            return (Criteria) this;
        }

        public Criteria andIsextendIsNull() {
            addCriterion("ISEXTEND is null");
            return (Criteria) this;
        }

        public Criteria andIsextendIsNotNull() {
            addCriterion("ISEXTEND is not null");
            return (Criteria) this;
        }

        public Criteria andIsextendEqualTo(String value) {
            addCriterion("ISEXTEND =", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendNotEqualTo(String value) {
            addCriterion("ISEXTEND <>", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendGreaterThan(String value) {
            addCriterion("ISEXTEND >", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendGreaterThanOrEqualTo(String value) {
            addCriterion("ISEXTEND >=", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendLessThan(String value) {
            addCriterion("ISEXTEND <", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendLessThanOrEqualTo(String value) {
            addCriterion("ISEXTEND <=", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendLike(String value) {
            addCriterion("ISEXTEND like", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendNotLike(String value) {
            addCriterion("ISEXTEND not like", value, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendIn(List<String> values) {
            addCriterion("ISEXTEND in", values, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendNotIn(List<String> values) {
            addCriterion("ISEXTEND not in", values, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendBetween(String value1, String value2) {
            addCriterion("ISEXTEND between", value1, value2, "isextend");
            return (Criteria) this;
        }

        public Criteria andIsextendNotBetween(String value1, String value2) {
            addCriterion("ISEXTEND not between", value1, value2, "isextend");
            return (Criteria) this;
        }

        public Criteria andZcdmIsNull() {
            addCriterion("ZCDM is null");
            return (Criteria) this;
        }

        public Criteria andZcdmIsNotNull() {
            addCriterion("ZCDM is not null");
            return (Criteria) this;
        }

        public Criteria andZcdmEqualTo(String value) {
            addCriterion("ZCDM =", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmNotEqualTo(String value) {
            addCriterion("ZCDM <>", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmGreaterThan(String value) {
            addCriterion("ZCDM >", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmGreaterThanOrEqualTo(String value) {
            addCriterion("ZCDM >=", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmLessThan(String value) {
            addCriterion("ZCDM <", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmLessThanOrEqualTo(String value) {
            addCriterion("ZCDM <=", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmLike(String value) {
            addCriterion("ZCDM like", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmNotLike(String value) {
            addCriterion("ZCDM not like", value, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmIn(List<String> values) {
            addCriterion("ZCDM in", values, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmNotIn(List<String> values) {
            addCriterion("ZCDM not in", values, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmBetween(String value1, String value2) {
            addCriterion("ZCDM between", value1, value2, "zcdm");
            return (Criteria) this;
        }

        public Criteria andZcdmNotBetween(String value1, String value2) {
            addCriterion("ZCDM not between", value1, value2, "zcdm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_code_elevator
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_code_elevator
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}