package com.jorchi.elevator.orm.model;

import java.util.Date;

public class Org {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SCODE
     *
     * @mbggenerated
     */
    private String scode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SNAME
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SDESCRIPTION
     *
     * @mbggenerated
     */
    private String sdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SREMARK
     *
     * @mbggenerated
     */
    private String sremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SCREATOR
     *
     * @mbggenerated
     */
    private Long screator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SCREATETIME
     *
     * @mbggenerated
     */
    private Date screatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SMODIFIER
     *
     * @mbggenerated
     */
    private Long smodifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SMODIFYTIME
     *
     * @mbggenerated
     */
    private Date smodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.STYPE
     *
     * @mbggenerated
     */
    private String stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SSTATE
     *
     * @mbggenerated
     */
    private Long sstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SLEVEL
     *
     * @mbggenerated
     */
    private String slevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SORDINAL
     *
     * @mbggenerated
     */
    private String sordinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SSYSTEM
     *
     * @mbggenerated
     */
    private String ssystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.SENABLED
     *
     * @mbggenerated
     */
    private String senabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.PARENTID
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.OWNERID
     *
     * @mbggenerated
     */
    private Long ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.LONGCODE
     *
     * @mbggenerated
     */
    private String longcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public Org(Integer id, String scode, String sname, String sdescription, String sremark, Long screator, Date screatetime, Long smodifier, Date smodifytime, String stype, Long sstate, String slevel, String sordinal, String ssystem, String senabled, Long parentid, Long ownerid, String longcode) {
        this.id = id;
        this.scode = scode;
        this.sname = sname;
        this.sdescription = sdescription;
        this.sremark = sremark;
        this.screator = screator;
        this.screatetime = screatetime;
        this.smodifier = smodifier;
        this.smodifytime = smodifytime;
        this.stype = stype;
        this.sstate = sstate;
        this.slevel = slevel;
        this.sordinal = sordinal;
        this.ssystem = ssystem;
        this.senabled = senabled;
        this.parentid = parentid;
        this.ownerid = ownerid;
        this.longcode = longcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public Org() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ID
     *
     * @return the value of sys_org.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ID
     *
     * @param id the value for sys_org.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SCODE
     *
     * @return the value of sys_org.SCODE
     *
     * @mbggenerated
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SCODE
     *
     * @param scode the value for sys_org.SCODE
     *
     * @mbggenerated
     */
    public void setScode(String scode) {
        this.scode = scode == null ? null : scode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SNAME
     *
     * @return the value of sys_org.SNAME
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SNAME
     *
     * @param sname the value for sys_org.SNAME
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SDESCRIPTION
     *
     * @return the value of sys_org.SDESCRIPTION
     *
     * @mbggenerated
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SDESCRIPTION
     *
     * @param sdescription the value for sys_org.SDESCRIPTION
     *
     * @mbggenerated
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription == null ? null : sdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SREMARK
     *
     * @return the value of sys_org.SREMARK
     *
     * @mbggenerated
     */
    public String getSremark() {
        return sremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SREMARK
     *
     * @param sremark the value for sys_org.SREMARK
     *
     * @mbggenerated
     */
    public void setSremark(String sremark) {
        this.sremark = sremark == null ? null : sremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SCREATOR
     *
     * @return the value of sys_org.SCREATOR
     *
     * @mbggenerated
     */
    public Long getScreator() {
        return screator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SCREATOR
     *
     * @param screator the value for sys_org.SCREATOR
     *
     * @mbggenerated
     */
    public void setScreator(Long screator) {
        this.screator = screator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SCREATETIME
     *
     * @return the value of sys_org.SCREATETIME
     *
     * @mbggenerated
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SCREATETIME
     *
     * @param screatetime the value for sys_org.SCREATETIME
     *
     * @mbggenerated
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SMODIFIER
     *
     * @return the value of sys_org.SMODIFIER
     *
     * @mbggenerated
     */
    public Long getSmodifier() {
        return smodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SMODIFIER
     *
     * @param smodifier the value for sys_org.SMODIFIER
     *
     * @mbggenerated
     */
    public void setSmodifier(Long smodifier) {
        this.smodifier = smodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SMODIFYTIME
     *
     * @return the value of sys_org.SMODIFYTIME
     *
     * @mbggenerated
     */
    public Date getSmodifytime() {
        return smodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SMODIFYTIME
     *
     * @param smodifytime the value for sys_org.SMODIFYTIME
     *
     * @mbggenerated
     */
    public void setSmodifytime(Date smodifytime) {
        this.smodifytime = smodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.STYPE
     *
     * @return the value of sys_org.STYPE
     *
     * @mbggenerated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.STYPE
     *
     * @param stype the value for sys_org.STYPE
     *
     * @mbggenerated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SSTATE
     *
     * @return the value of sys_org.SSTATE
     *
     * @mbggenerated
     */
    public Long getSstate() {
        return sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SSTATE
     *
     * @param sstate the value for sys_org.SSTATE
     *
     * @mbggenerated
     */
    public void setSstate(Long sstate) {
        this.sstate = sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SLEVEL
     *
     * @return the value of sys_org.SLEVEL
     *
     * @mbggenerated
     */
    public String getSlevel() {
        return slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SLEVEL
     *
     * @param slevel the value for sys_org.SLEVEL
     *
     * @mbggenerated
     */
    public void setSlevel(String slevel) {
        this.slevel = slevel == null ? null : slevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SORDINAL
     *
     * @return the value of sys_org.SORDINAL
     *
     * @mbggenerated
     */
    public String getSordinal() {
        return sordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SORDINAL
     *
     * @param sordinal the value for sys_org.SORDINAL
     *
     * @mbggenerated
     */
    public void setSordinal(String sordinal) {
        this.sordinal = sordinal == null ? null : sordinal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SSYSTEM
     *
     * @return the value of sys_org.SSYSTEM
     *
     * @mbggenerated
     */
    public String getSsystem() {
        return ssystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SSYSTEM
     *
     * @param ssystem the value for sys_org.SSYSTEM
     *
     * @mbggenerated
     */
    public void setSsystem(String ssystem) {
        this.ssystem = ssystem == null ? null : ssystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.SENABLED
     *
     * @return the value of sys_org.SENABLED
     *
     * @mbggenerated
     */
    public String getSenabled() {
        return senabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.SENABLED
     *
     * @param senabled the value for sys_org.SENABLED
     *
     * @mbggenerated
     */
    public void setSenabled(String senabled) {
        this.senabled = senabled == null ? null : senabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.PARENTID
     *
     * @return the value of sys_org.PARENTID
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.PARENTID
     *
     * @param parentid the value for sys_org.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.OWNERID
     *
     * @return the value of sys_org.OWNERID
     *
     * @mbggenerated
     */
    public Long getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.OWNERID
     *
     * @param ownerid the value for sys_org.OWNERID
     *
     * @mbggenerated
     */
    public void setOwnerid(Long ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.LONGCODE
     *
     * @return the value of sys_org.LONGCODE
     *
     * @mbggenerated
     */
    public String getLongcode() {
        return longcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.LONGCODE
     *
     * @param longcode the value for sys_org.LONGCODE
     *
     * @mbggenerated
     */
    public void setLongcode(String longcode) {
        this.longcode = longcode == null ? null : longcode.trim();
    }
}