package com.jorchi.elevator.orm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public OrgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andScodeIsNull() {
            addCriterion("SCODE is null");
            return (Criteria) this;
        }

        public Criteria andScodeIsNotNull() {
            addCriterion("SCODE is not null");
            return (Criteria) this;
        }

        public Criteria andScodeEqualTo(String value) {
            addCriterion("SCODE =", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotEqualTo(String value) {
            addCriterion("SCODE <>", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeGreaterThan(String value) {
            addCriterion("SCODE >", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeGreaterThanOrEqualTo(String value) {
            addCriterion("SCODE >=", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLessThan(String value) {
            addCriterion("SCODE <", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLessThanOrEqualTo(String value) {
            addCriterion("SCODE <=", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeLike(String value) {
            addCriterion("SCODE like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotLike(String value) {
            addCriterion("SCODE not like", value, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeIn(List<String> values) {
            addCriterion("SCODE in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotIn(List<String> values) {
            addCriterion("SCODE not in", values, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeBetween(String value1, String value2) {
            addCriterion("SCODE between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andScodeNotBetween(String value1, String value2) {
            addCriterion("SCODE not between", value1, value2, "scode");
            return (Criteria) this;
        }

        public Criteria andSnameIsNull() {
            addCriterion("SNAME is null");
            return (Criteria) this;
        }

        public Criteria andSnameIsNotNull() {
            addCriterion("SNAME is not null");
            return (Criteria) this;
        }

        public Criteria andSnameEqualTo(String value) {
            addCriterion("SNAME =", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotEqualTo(String value) {
            addCriterion("SNAME <>", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThan(String value) {
            addCriterion("SNAME >", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThanOrEqualTo(String value) {
            addCriterion("SNAME >=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThan(String value) {
            addCriterion("SNAME <", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThanOrEqualTo(String value) {
            addCriterion("SNAME <=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLike(String value) {
            addCriterion("SNAME like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotLike(String value) {
            addCriterion("SNAME not like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameIn(List<String> values) {
            addCriterion("SNAME in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotIn(List<String> values) {
            addCriterion("SNAME not in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameBetween(String value1, String value2) {
            addCriterion("SNAME between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotBetween(String value1, String value2) {
            addCriterion("SNAME not between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSdescriptionIsNull() {
            addCriterion("SDESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andSdescriptionIsNotNull() {
            addCriterion("SDESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andSdescriptionEqualTo(String value) {
            addCriterion("SDESCRIPTION =", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotEqualTo(String value) {
            addCriterion("SDESCRIPTION <>", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionGreaterThan(String value) {
            addCriterion("SDESCRIPTION >", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("SDESCRIPTION >=", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionLessThan(String value) {
            addCriterion("SDESCRIPTION <", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionLessThanOrEqualTo(String value) {
            addCriterion("SDESCRIPTION <=", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionLike(String value) {
            addCriterion("SDESCRIPTION like", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotLike(String value) {
            addCriterion("SDESCRIPTION not like", value, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionIn(List<String> values) {
            addCriterion("SDESCRIPTION in", values, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotIn(List<String> values) {
            addCriterion("SDESCRIPTION not in", values, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionBetween(String value1, String value2) {
            addCriterion("SDESCRIPTION between", value1, value2, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSdescriptionNotBetween(String value1, String value2) {
            addCriterion("SDESCRIPTION not between", value1, value2, "sdescription");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNull() {
            addCriterion("SREMARK is null");
            return (Criteria) this;
        }

        public Criteria andSremarkIsNotNull() {
            addCriterion("SREMARK is not null");
            return (Criteria) this;
        }

        public Criteria andSremarkEqualTo(String value) {
            addCriterion("SREMARK =", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotEqualTo(String value) {
            addCriterion("SREMARK <>", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkGreaterThan(String value) {
            addCriterion("SREMARK >", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkGreaterThanOrEqualTo(String value) {
            addCriterion("SREMARK >=", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLessThan(String value) {
            addCriterion("SREMARK <", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLessThanOrEqualTo(String value) {
            addCriterion("SREMARK <=", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkLike(String value) {
            addCriterion("SREMARK like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotLike(String value) {
            addCriterion("SREMARK not like", value, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkIn(List<String> values) {
            addCriterion("SREMARK in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotIn(List<String> values) {
            addCriterion("SREMARK not in", values, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkBetween(String value1, String value2) {
            addCriterion("SREMARK between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andSremarkNotBetween(String value1, String value2) {
            addCriterion("SREMARK not between", value1, value2, "sremark");
            return (Criteria) this;
        }

        public Criteria andScreatorIsNull() {
            addCriterion("SCREATOR is null");
            return (Criteria) this;
        }

        public Criteria andScreatorIsNotNull() {
            addCriterion("SCREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andScreatorEqualTo(Long value) {
            addCriterion("SCREATOR =", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotEqualTo(Long value) {
            addCriterion("SCREATOR <>", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorGreaterThan(Long value) {
            addCriterion("SCREATOR >", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("SCREATOR >=", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorLessThan(Long value) {
            addCriterion("SCREATOR <", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorLessThanOrEqualTo(Long value) {
            addCriterion("SCREATOR <=", value, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorIn(List<Long> values) {
            addCriterion("SCREATOR in", values, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotIn(List<Long> values) {
            addCriterion("SCREATOR not in", values, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorBetween(Long value1, Long value2) {
            addCriterion("SCREATOR between", value1, value2, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatorNotBetween(Long value1, Long value2) {
            addCriterion("SCREATOR not between", value1, value2, "screator");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIsNull() {
            addCriterion("SCREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIsNotNull() {
            addCriterion("SCREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andScreatetimeEqualTo(Date value) {
            addCriterion("SCREATETIME =", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotEqualTo(Date value) {
            addCriterion("SCREATETIME <>", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeGreaterThan(Date value) {
            addCriterion("SCREATETIME >", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SCREATETIME >=", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeLessThan(Date value) {
            addCriterion("SCREATETIME <", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("SCREATETIME <=", value, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeIn(List<Date> values) {
            addCriterion("SCREATETIME in", values, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotIn(List<Date> values) {
            addCriterion("SCREATETIME not in", values, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeBetween(Date value1, Date value2) {
            addCriterion("SCREATETIME between", value1, value2, "screatetime");
            return (Criteria) this;
        }

        public Criteria andScreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("SCREATETIME not between", value1, value2, "screatetime");
            return (Criteria) this;
        }

        public Criteria andSmodifierIsNull() {
            addCriterion("SMODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andSmodifierIsNotNull() {
            addCriterion("SMODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andSmodifierEqualTo(Long value) {
            addCriterion("SMODIFIER =", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotEqualTo(Long value) {
            addCriterion("SMODIFIER <>", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierGreaterThan(Long value) {
            addCriterion("SMODIFIER >", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierGreaterThanOrEqualTo(Long value) {
            addCriterion("SMODIFIER >=", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierLessThan(Long value) {
            addCriterion("SMODIFIER <", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierLessThanOrEqualTo(Long value) {
            addCriterion("SMODIFIER <=", value, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierIn(List<Long> values) {
            addCriterion("SMODIFIER in", values, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotIn(List<Long> values) {
            addCriterion("SMODIFIER not in", values, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierBetween(Long value1, Long value2) {
            addCriterion("SMODIFIER between", value1, value2, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifierNotBetween(Long value1, Long value2) {
            addCriterion("SMODIFIER not between", value1, value2, "smodifier");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIsNull() {
            addCriterion("SMODIFYTIME is null");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIsNotNull() {
            addCriterion("SMODIFYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeEqualTo(Date value) {
            addCriterion("SMODIFYTIME =", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotEqualTo(Date value) {
            addCriterion("SMODIFYTIME <>", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeGreaterThan(Date value) {
            addCriterion("SMODIFYTIME >", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMODIFYTIME >=", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeLessThan(Date value) {
            addCriterion("SMODIFYTIME <", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeLessThanOrEqualTo(Date value) {
            addCriterion("SMODIFYTIME <=", value, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeIn(List<Date> values) {
            addCriterion("SMODIFYTIME in", values, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotIn(List<Date> values) {
            addCriterion("SMODIFYTIME not in", values, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeBetween(Date value1, Date value2) {
            addCriterion("SMODIFYTIME between", value1, value2, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andSmodifytimeNotBetween(Date value1, Date value2) {
            addCriterion("SMODIFYTIME not between", value1, value2, "smodifytime");
            return (Criteria) this;
        }

        public Criteria andStypeIsNull() {
            addCriterion("STYPE is null");
            return (Criteria) this;
        }

        public Criteria andStypeIsNotNull() {
            addCriterion("STYPE is not null");
            return (Criteria) this;
        }

        public Criteria andStypeEqualTo(String value) {
            addCriterion("STYPE =", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotEqualTo(String value) {
            addCriterion("STYPE <>", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThan(String value) {
            addCriterion("STYPE >", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeGreaterThanOrEqualTo(String value) {
            addCriterion("STYPE >=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThan(String value) {
            addCriterion("STYPE <", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLessThanOrEqualTo(String value) {
            addCriterion("STYPE <=", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeLike(String value) {
            addCriterion("STYPE like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotLike(String value) {
            addCriterion("STYPE not like", value, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeIn(List<String> values) {
            addCriterion("STYPE in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotIn(List<String> values) {
            addCriterion("STYPE not in", values, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeBetween(String value1, String value2) {
            addCriterion("STYPE between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andStypeNotBetween(String value1, String value2) {
            addCriterion("STYPE not between", value1, value2, "stype");
            return (Criteria) this;
        }

        public Criteria andSstateIsNull() {
            addCriterion("SSTATE is null");
            return (Criteria) this;
        }

        public Criteria andSstateIsNotNull() {
            addCriterion("SSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andSstateEqualTo(Long value) {
            addCriterion("SSTATE =", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotEqualTo(Long value) {
            addCriterion("SSTATE <>", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateGreaterThan(Long value) {
            addCriterion("SSTATE >", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateGreaterThanOrEqualTo(Long value) {
            addCriterion("SSTATE >=", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateLessThan(Long value) {
            addCriterion("SSTATE <", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateLessThanOrEqualTo(Long value) {
            addCriterion("SSTATE <=", value, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateIn(List<Long> values) {
            addCriterion("SSTATE in", values, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotIn(List<Long> values) {
            addCriterion("SSTATE not in", values, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateBetween(Long value1, Long value2) {
            addCriterion("SSTATE between", value1, value2, "sstate");
            return (Criteria) this;
        }

        public Criteria andSstateNotBetween(Long value1, Long value2) {
            addCriterion("SSTATE not between", value1, value2, "sstate");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNull() {
            addCriterion("SLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSlevelIsNotNull() {
            addCriterion("SLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSlevelEqualTo(String value) {
            addCriterion("SLEVEL =", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotEqualTo(String value) {
            addCriterion("SLEVEL <>", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThan(String value) {
            addCriterion("SLEVEL >", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelGreaterThanOrEqualTo(String value) {
            addCriterion("SLEVEL >=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThan(String value) {
            addCriterion("SLEVEL <", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLessThanOrEqualTo(String value) {
            addCriterion("SLEVEL <=", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelLike(String value) {
            addCriterion("SLEVEL like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotLike(String value) {
            addCriterion("SLEVEL not like", value, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelIn(List<String> values) {
            addCriterion("SLEVEL in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotIn(List<String> values) {
            addCriterion("SLEVEL not in", values, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelBetween(String value1, String value2) {
            addCriterion("SLEVEL between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSlevelNotBetween(String value1, String value2) {
            addCriterion("SLEVEL not between", value1, value2, "slevel");
            return (Criteria) this;
        }

        public Criteria andSordinalIsNull() {
            addCriterion("SORDINAL is null");
            return (Criteria) this;
        }

        public Criteria andSordinalIsNotNull() {
            addCriterion("SORDINAL is not null");
            return (Criteria) this;
        }

        public Criteria andSordinalEqualTo(String value) {
            addCriterion("SORDINAL =", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotEqualTo(String value) {
            addCriterion("SORDINAL <>", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalGreaterThan(String value) {
            addCriterion("SORDINAL >", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalGreaterThanOrEqualTo(String value) {
            addCriterion("SORDINAL >=", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLessThan(String value) {
            addCriterion("SORDINAL <", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLessThanOrEqualTo(String value) {
            addCriterion("SORDINAL <=", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalLike(String value) {
            addCriterion("SORDINAL like", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotLike(String value) {
            addCriterion("SORDINAL not like", value, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalIn(List<String> values) {
            addCriterion("SORDINAL in", values, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotIn(List<String> values) {
            addCriterion("SORDINAL not in", values, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalBetween(String value1, String value2) {
            addCriterion("SORDINAL between", value1, value2, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSordinalNotBetween(String value1, String value2) {
            addCriterion("SORDINAL not between", value1, value2, "sordinal");
            return (Criteria) this;
        }

        public Criteria andSsystemIsNull() {
            addCriterion("SSYSTEM is null");
            return (Criteria) this;
        }

        public Criteria andSsystemIsNotNull() {
            addCriterion("SSYSTEM is not null");
            return (Criteria) this;
        }

        public Criteria andSsystemEqualTo(String value) {
            addCriterion("SSYSTEM =", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotEqualTo(String value) {
            addCriterion("SSYSTEM <>", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemGreaterThan(String value) {
            addCriterion("SSYSTEM >", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemGreaterThanOrEqualTo(String value) {
            addCriterion("SSYSTEM >=", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLessThan(String value) {
            addCriterion("SSYSTEM <", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLessThanOrEqualTo(String value) {
            addCriterion("SSYSTEM <=", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemLike(String value) {
            addCriterion("SSYSTEM like", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotLike(String value) {
            addCriterion("SSYSTEM not like", value, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemIn(List<String> values) {
            addCriterion("SSYSTEM in", values, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotIn(List<String> values) {
            addCriterion("SSYSTEM not in", values, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemBetween(String value1, String value2) {
            addCriterion("SSYSTEM between", value1, value2, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSsystemNotBetween(String value1, String value2) {
            addCriterion("SSYSTEM not between", value1, value2, "ssystem");
            return (Criteria) this;
        }

        public Criteria andSenabledIsNull() {
            addCriterion("SENABLED is null");
            return (Criteria) this;
        }

        public Criteria andSenabledIsNotNull() {
            addCriterion("SENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andSenabledEqualTo(String value) {
            addCriterion("SENABLED =", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotEqualTo(String value) {
            addCriterion("SENABLED <>", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledGreaterThan(String value) {
            addCriterion("SENABLED >", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledGreaterThanOrEqualTo(String value) {
            addCriterion("SENABLED >=", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLessThan(String value) {
            addCriterion("SENABLED <", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLessThanOrEqualTo(String value) {
            addCriterion("SENABLED <=", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledLike(String value) {
            addCriterion("SENABLED like", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotLike(String value) {
            addCriterion("SENABLED not like", value, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledIn(List<String> values) {
            addCriterion("SENABLED in", values, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotIn(List<String> values) {
            addCriterion("SENABLED not in", values, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledBetween(String value1, String value2) {
            addCriterion("SENABLED between", value1, value2, "senabled");
            return (Criteria) this;
        }

        public Criteria andSenabledNotBetween(String value1, String value2) {
            addCriterion("SENABLED not between", value1, value2, "senabled");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("PARENTID is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("PARENTID is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Long value) {
            addCriterion("PARENTID =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Long value) {
            addCriterion("PARENTID <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Long value) {
            addCriterion("PARENTID >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENTID >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Long value) {
            addCriterion("PARENTID <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Long value) {
            addCriterion("PARENTID <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Long> values) {
            addCriterion("PARENTID in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Long> values) {
            addCriterion("PARENTID not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Long value1, Long value2) {
            addCriterion("PARENTID between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Long value1, Long value2) {
            addCriterion("PARENTID not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andOwneridIsNull() {
            addCriterion("OWNERID is null");
            return (Criteria) this;
        }

        public Criteria andOwneridIsNotNull() {
            addCriterion("OWNERID is not null");
            return (Criteria) this;
        }

        public Criteria andOwneridEqualTo(Long value) {
            addCriterion("OWNERID =", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotEqualTo(Long value) {
            addCriterion("OWNERID <>", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridGreaterThan(Long value) {
            addCriterion("OWNERID >", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridGreaterThanOrEqualTo(Long value) {
            addCriterion("OWNERID >=", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridLessThan(Long value) {
            addCriterion("OWNERID <", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridLessThanOrEqualTo(Long value) {
            addCriterion("OWNERID <=", value, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridIn(List<Long> values) {
            addCriterion("OWNERID in", values, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotIn(List<Long> values) {
            addCriterion("OWNERID not in", values, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridBetween(Long value1, Long value2) {
            addCriterion("OWNERID between", value1, value2, "ownerid");
            return (Criteria) this;
        }

        public Criteria andOwneridNotBetween(Long value1, Long value2) {
            addCriterion("OWNERID not between", value1, value2, "ownerid");
            return (Criteria) this;
        }

        public Criteria andLongcodeIsNull() {
            addCriterion("LONGCODE is null");
            return (Criteria) this;
        }

        public Criteria andLongcodeIsNotNull() {
            addCriterion("LONGCODE is not null");
            return (Criteria) this;
        }

        public Criteria andLongcodeEqualTo(String value) {
            addCriterion("LONGCODE =", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeNotEqualTo(String value) {
            addCriterion("LONGCODE <>", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeGreaterThan(String value) {
            addCriterion("LONGCODE >", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeGreaterThanOrEqualTo(String value) {
            addCriterion("LONGCODE >=", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeLessThan(String value) {
            addCriterion("LONGCODE <", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeLessThanOrEqualTo(String value) {
            addCriterion("LONGCODE <=", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeLike(String value) {
            addCriterion("LONGCODE like", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeNotLike(String value) {
            addCriterion("LONGCODE not like", value, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeIn(List<String> values) {
            addCriterion("LONGCODE in", values, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeNotIn(List<String> values) {
            addCriterion("LONGCODE not in", values, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeBetween(String value1, String value2) {
            addCriterion("LONGCODE between", value1, value2, "longcode");
            return (Criteria) this;
        }

        public Criteria andLongcodeNotBetween(String value1, String value2) {
            addCriterion("LONGCODE not between", value1, value2, "longcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_org
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_org
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}