package com.jorchi.elevator.orm.model;

import java.math.BigDecimal;
import java.util.Date;

public class UList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SCODE
     *
     * @mbggenerated
     */
    private String scode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SNAME
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SDESCRIPTION
     *
     * @mbggenerated
     */
    private String sdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SQRCODE
     *
     * @mbggenerated
     */
    private String sqrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.PHOTOPATH
     *
     * @mbggenerated
     */
    private String photopath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.OTHEREXPLAIN
     *
     * @mbggenerated
     */
    private String otherexplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.URLPHOTO
     *
     * @mbggenerated
     */
    private String urlphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.GPSADDRESS
     *
     * @mbggenerated
     */
    private String gpsaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SCOMMENT
     *
     * @mbggenerated
     */
    private String scomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.RECORDPATH
     *
     * @mbggenerated
     */
    private String recordpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.URLRECORD
     *
     * @mbggenerated
     */
    private String urlrecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.STYPE
     *
     * @mbggenerated
     */
    private String stype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SNORMAL
     *
     * @mbggenerated
     */
    private String snormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.CHECKSTATUS
     *
     * @mbggenerated
     */
    private String checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SISSUETYPE
     *
     * @mbggenerated
     */
    private String sissuetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TEXTCONTENT
     *
     * @mbggenerated
     */
    private String textcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TEXTCHECK
     *
     * @mbggenerated
     */
    private String textcheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SUBMITTIME
     *
     * @mbggenerated
     */
    private Date submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.CHECKTIME
     *
     * @mbggenerated
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.PHOTOTIME
     *
     * @mbggenerated
     */
    private Date phototime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.RECORDTIME
     *
     * @mbggenerated
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.CODEID
     *
     * @mbggenerated
     */
    private Integer codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TASKID
     *
     * @mbggenerated
     */
    private Integer taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SUBMITTERID
     *
     * @mbggenerated
     */
    private Integer submitterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.CHECKERID
     *
     * @mbggenerated
     */
    private Long checkerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.GPSX
     *
     * @mbggenerated
     */
    private BigDecimal gpsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.GPSY
     *
     * @mbggenerated
     */
    private BigDecimal gpsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.FOLLOWIDS
     *
     * @mbggenerated
     */
    private String followids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.HAS_SEND
     *
     * @mbggenerated
     */
    private Integer hasSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.LOG_PATROL
     *
     * @mbggenerated
     */
    private String logPatrol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.LOG_IMAGE
     *
     * @mbggenerated
     */
    private String logImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.BEGINTIME
     *
     * @mbggenerated
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.PROBTYPEID
     *
     * @mbggenerated
     */
    private Long probtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.SRANKTYPE
     *
     * @mbggenerated
     */
    private String sranktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TRAPPED
     *
     * @mbggenerated
     */
    private String trapped;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.MISINFORMATION
     *
     * @mbggenerated
     */
    private String misinformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.OVERNIGHT
     *
     * @mbggenerated
     */
    private String overnight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TOKEN
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.UPDATESTATUS
     *
     * @mbggenerated
     */
    private Integer updatestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.jg_time
     *
     * @mbggenerated
     */
    private Integer jgTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TEMPTASK
     *
     * @mbggenerated
     */
    private Boolean temptask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.TARGETUSERID
     *
     * @mbggenerated
     */
    private Integer targetuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_list.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    public UList(Integer id, String scode, String sname, String sdescription, String sqrcode, String photopath, String otherexplain, String urlphoto, String gpsaddress, String scomment, String recordpath, String urlrecord, String stype, String snormal, String checkstatus, String sissuetype, String textcontent, String textcheck, Date submittime, Date checktime, Date phototime, Date recordtime, Integer codeid, Integer taskid, Integer submitterid, Long checkerid, BigDecimal gpsx, BigDecimal gpsy, String followids, Integer hasSend, String logPatrol, String logImage, Date begintime, Long probtypeid, String sranktype, String trapped, String misinformation, String overnight, String token, Integer updatestatus, Integer jgTime, Boolean temptask, Integer targetuserid, Date auditTime) {
        this.id = id;
        this.scode = scode;
        this.sname = sname;
        this.sdescription = sdescription;
        this.sqrcode = sqrcode;
        this.photopath = photopath;
        this.otherexplain = otherexplain;
        this.urlphoto = urlphoto;
        this.gpsaddress = gpsaddress;
        this.scomment = scomment;
        this.recordpath = recordpath;
        this.urlrecord = urlrecord;
        this.stype = stype;
        this.snormal = snormal;
        this.checkstatus = checkstatus;
        this.sissuetype = sissuetype;
        this.textcontent = textcontent;
        this.textcheck = textcheck;
        this.submittime = submittime;
        this.checktime = checktime;
        this.phototime = phototime;
        this.recordtime = recordtime;
        this.codeid = codeid;
        this.taskid = taskid;
        this.submitterid = submitterid;
        this.checkerid = checkerid;
        this.gpsx = gpsx;
        this.gpsy = gpsy;
        this.followids = followids;
        this.hasSend = hasSend;
        this.logPatrol = logPatrol;
        this.logImage = logImage;
        this.begintime = begintime;
        this.probtypeid = probtypeid;
        this.sranktype = sranktype;
        this.trapped = trapped;
        this.misinformation = misinformation;
        this.overnight = overnight;
        this.token = token;
        this.updatestatus = updatestatus;
        this.jgTime = jgTime;
        this.temptask = temptask;
        this.targetuserid = targetuserid;
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_list
     *
     * @mbggenerated
     */
    public UList() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.ID
     *
     * @return the value of u_list.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.ID
     *
     * @param id the value for u_list.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SCODE
     *
     * @return the value of u_list.SCODE
     *
     * @mbggenerated
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SCODE
     *
     * @param scode the value for u_list.SCODE
     *
     * @mbggenerated
     */
    public void setScode(String scode) {
        this.scode = scode == null ? null : scode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SNAME
     *
     * @return the value of u_list.SNAME
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SNAME
     *
     * @param sname the value for u_list.SNAME
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SDESCRIPTION
     *
     * @return the value of u_list.SDESCRIPTION
     *
     * @mbggenerated
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SDESCRIPTION
     *
     * @param sdescription the value for u_list.SDESCRIPTION
     *
     * @mbggenerated
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription == null ? null : sdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SQRCODE
     *
     * @return the value of u_list.SQRCODE
     *
     * @mbggenerated
     */
    public String getSqrcode() {
        return sqrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SQRCODE
     *
     * @param sqrcode the value for u_list.SQRCODE
     *
     * @mbggenerated
     */
    public void setSqrcode(String sqrcode) {
        this.sqrcode = sqrcode == null ? null : sqrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.PHOTOPATH
     *
     * @return the value of u_list.PHOTOPATH
     *
     * @mbggenerated
     */
    public String getPhotopath() {
        return photopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.PHOTOPATH
     *
     * @param photopath the value for u_list.PHOTOPATH
     *
     * @mbggenerated
     */
    public void setPhotopath(String photopath) {
        this.photopath = photopath == null ? null : photopath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.OTHEREXPLAIN
     *
     * @return the value of u_list.OTHEREXPLAIN
     *
     * @mbggenerated
     */
    public String getOtherexplain() {
        return otherexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.OTHEREXPLAIN
     *
     * @param otherexplain the value for u_list.OTHEREXPLAIN
     *
     * @mbggenerated
     */
    public void setOtherexplain(String otherexplain) {
        this.otherexplain = otherexplain == null ? null : otherexplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.URLPHOTO
     *
     * @return the value of u_list.URLPHOTO
     *
     * @mbggenerated
     */
    public String getUrlphoto() {
        return urlphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.URLPHOTO
     *
     * @param urlphoto the value for u_list.URLPHOTO
     *
     * @mbggenerated
     */
    public void setUrlphoto(String urlphoto) {
        this.urlphoto = urlphoto == null ? null : urlphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.GPSADDRESS
     *
     * @return the value of u_list.GPSADDRESS
     *
     * @mbggenerated
     */
    public String getGpsaddress() {
        return gpsaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.GPSADDRESS
     *
     * @param gpsaddress the value for u_list.GPSADDRESS
     *
     * @mbggenerated
     */
    public void setGpsaddress(String gpsaddress) {
        this.gpsaddress = gpsaddress == null ? null : gpsaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SCOMMENT
     *
     * @return the value of u_list.SCOMMENT
     *
     * @mbggenerated
     */
    public String getScomment() {
        return scomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SCOMMENT
     *
     * @param scomment the value for u_list.SCOMMENT
     *
     * @mbggenerated
     */
    public void setScomment(String scomment) {
        this.scomment = scomment == null ? null : scomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.RECORDPATH
     *
     * @return the value of u_list.RECORDPATH
     *
     * @mbggenerated
     */
    public String getRecordpath() {
        return recordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.RECORDPATH
     *
     * @param recordpath the value for u_list.RECORDPATH
     *
     * @mbggenerated
     */
    public void setRecordpath(String recordpath) {
        this.recordpath = recordpath == null ? null : recordpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.URLRECORD
     *
     * @return the value of u_list.URLRECORD
     *
     * @mbggenerated
     */
    public String getUrlrecord() {
        return urlrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.URLRECORD
     *
     * @param urlrecord the value for u_list.URLRECORD
     *
     * @mbggenerated
     */
    public void setUrlrecord(String urlrecord) {
        this.urlrecord = urlrecord == null ? null : urlrecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.STYPE
     *
     * @return the value of u_list.STYPE
     *
     * @mbggenerated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.STYPE
     *
     * @param stype the value for u_list.STYPE
     *
     * @mbggenerated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SNORMAL
     *
     * @return the value of u_list.SNORMAL
     *
     * @mbggenerated
     */
    public String getSnormal() {
        return snormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SNORMAL
     *
     * @param snormal the value for u_list.SNORMAL
     *
     * @mbggenerated
     */
    public void setSnormal(String snormal) {
        this.snormal = snormal == null ? null : snormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.CHECKSTATUS
     *
     * @return the value of u_list.CHECKSTATUS
     *
     * @mbggenerated
     */
    public String getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.CHECKSTATUS
     *
     * @param checkstatus the value for u_list.CHECKSTATUS
     *
     * @mbggenerated
     */
    public void setCheckstatus(String checkstatus) {
        this.checkstatus = checkstatus == null ? null : checkstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SISSUETYPE
     *
     * @return the value of u_list.SISSUETYPE
     *
     * @mbggenerated
     */
    public String getSissuetype() {
        return sissuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SISSUETYPE
     *
     * @param sissuetype the value for u_list.SISSUETYPE
     *
     * @mbggenerated
     */
    public void setSissuetype(String sissuetype) {
        this.sissuetype = sissuetype == null ? null : sissuetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TEXTCONTENT
     *
     * @return the value of u_list.TEXTCONTENT
     *
     * @mbggenerated
     */
    public String getTextcontent() {
        return textcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TEXTCONTENT
     *
     * @param textcontent the value for u_list.TEXTCONTENT
     *
     * @mbggenerated
     */
    public void setTextcontent(String textcontent) {
        this.textcontent = textcontent == null ? null : textcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TEXTCHECK
     *
     * @return the value of u_list.TEXTCHECK
     *
     * @mbggenerated
     */
    public String getTextcheck() {
        return textcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TEXTCHECK
     *
     * @param textcheck the value for u_list.TEXTCHECK
     *
     * @mbggenerated
     */
    public void setTextcheck(String textcheck) {
        this.textcheck = textcheck == null ? null : textcheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SUBMITTIME
     *
     * @return the value of u_list.SUBMITTIME
     *
     * @mbggenerated
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SUBMITTIME
     *
     * @param submittime the value for u_list.SUBMITTIME
     *
     * @mbggenerated
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.CHECKTIME
     *
     * @return the value of u_list.CHECKTIME
     *
     * @mbggenerated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.CHECKTIME
     *
     * @param checktime the value for u_list.CHECKTIME
     *
     * @mbggenerated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.PHOTOTIME
     *
     * @return the value of u_list.PHOTOTIME
     *
     * @mbggenerated
     */
    public Date getPhototime() {
        return phototime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.PHOTOTIME
     *
     * @param phototime the value for u_list.PHOTOTIME
     *
     * @mbggenerated
     */
    public void setPhototime(Date phototime) {
        this.phototime = phototime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.RECORDTIME
     *
     * @return the value of u_list.RECORDTIME
     *
     * @mbggenerated
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.RECORDTIME
     *
     * @param recordtime the value for u_list.RECORDTIME
     *
     * @mbggenerated
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.CODEID
     *
     * @return the value of u_list.CODEID
     *
     * @mbggenerated
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.CODEID
     *
     * @param codeid the value for u_list.CODEID
     *
     * @mbggenerated
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TASKID
     *
     * @return the value of u_list.TASKID
     *
     * @mbggenerated
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TASKID
     *
     * @param taskid the value for u_list.TASKID
     *
     * @mbggenerated
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SUBMITTERID
     *
     * @return the value of u_list.SUBMITTERID
     *
     * @mbggenerated
     */
    public Integer getSubmitterid() {
        return submitterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SUBMITTERID
     *
     * @param submitterid the value for u_list.SUBMITTERID
     *
     * @mbggenerated
     */
    public void setSubmitterid(Integer submitterid) {
        this.submitterid = submitterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.CHECKERID
     *
     * @return the value of u_list.CHECKERID
     *
     * @mbggenerated
     */
    public Long getCheckerid() {
        return checkerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.CHECKERID
     *
     * @param checkerid the value for u_list.CHECKERID
     *
     * @mbggenerated
     */
    public void setCheckerid(Long checkerid) {
        this.checkerid = checkerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.GPSX
     *
     * @return the value of u_list.GPSX
     *
     * @mbggenerated
     */
    public BigDecimal getGpsx() {
        return gpsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.GPSX
     *
     * @param gpsx the value for u_list.GPSX
     *
     * @mbggenerated
     */
    public void setGpsx(BigDecimal gpsx) {
        this.gpsx = gpsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.GPSY
     *
     * @return the value of u_list.GPSY
     *
     * @mbggenerated
     */
    public BigDecimal getGpsy() {
        return gpsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.GPSY
     *
     * @param gpsy the value for u_list.GPSY
     *
     * @mbggenerated
     */
    public void setGpsy(BigDecimal gpsy) {
        this.gpsy = gpsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.FOLLOWIDS
     *
     * @return the value of u_list.FOLLOWIDS
     *
     * @mbggenerated
     */
    public String getFollowids() {
        return followids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.FOLLOWIDS
     *
     * @param followids the value for u_list.FOLLOWIDS
     *
     * @mbggenerated
     */
    public void setFollowids(String followids) {
        this.followids = followids == null ? null : followids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.HAS_SEND
     *
     * @return the value of u_list.HAS_SEND
     *
     * @mbggenerated
     */
    public Integer getHasSend() {
        return hasSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.HAS_SEND
     *
     * @param hasSend the value for u_list.HAS_SEND
     *
     * @mbggenerated
     */
    public void setHasSend(Integer hasSend) {
        this.hasSend = hasSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.LOG_PATROL
     *
     * @return the value of u_list.LOG_PATROL
     *
     * @mbggenerated
     */
    public String getLogPatrol() {
        return logPatrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.LOG_PATROL
     *
     * @param logPatrol the value for u_list.LOG_PATROL
     *
     * @mbggenerated
     */
    public void setLogPatrol(String logPatrol) {
        this.logPatrol = logPatrol == null ? null : logPatrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.LOG_IMAGE
     *
     * @return the value of u_list.LOG_IMAGE
     *
     * @mbggenerated
     */
    public String getLogImage() {
        return logImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.LOG_IMAGE
     *
     * @param logImage the value for u_list.LOG_IMAGE
     *
     * @mbggenerated
     */
    public void setLogImage(String logImage) {
        this.logImage = logImage == null ? null : logImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.BEGINTIME
     *
     * @return the value of u_list.BEGINTIME
     *
     * @mbggenerated
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.BEGINTIME
     *
     * @param begintime the value for u_list.BEGINTIME
     *
     * @mbggenerated
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.PROBTYPEID
     *
     * @return the value of u_list.PROBTYPEID
     *
     * @mbggenerated
     */
    public Long getProbtypeid() {
        return probtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.PROBTYPEID
     *
     * @param probtypeid the value for u_list.PROBTYPEID
     *
     * @mbggenerated
     */
    public void setProbtypeid(Long probtypeid) {
        this.probtypeid = probtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.SRANKTYPE
     *
     * @return the value of u_list.SRANKTYPE
     *
     * @mbggenerated
     */
    public String getSranktype() {
        return sranktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.SRANKTYPE
     *
     * @param sranktype the value for u_list.SRANKTYPE
     *
     * @mbggenerated
     */
    public void setSranktype(String sranktype) {
        this.sranktype = sranktype == null ? null : sranktype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TRAPPED
     *
     * @return the value of u_list.TRAPPED
     *
     * @mbggenerated
     */
    public String getTrapped() {
        return trapped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TRAPPED
     *
     * @param trapped the value for u_list.TRAPPED
     *
     * @mbggenerated
     */
    public void setTrapped(String trapped) {
        this.trapped = trapped == null ? null : trapped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.MISINFORMATION
     *
     * @return the value of u_list.MISINFORMATION
     *
     * @mbggenerated
     */
    public String getMisinformation() {
        return misinformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.MISINFORMATION
     *
     * @param misinformation the value for u_list.MISINFORMATION
     *
     * @mbggenerated
     */
    public void setMisinformation(String misinformation) {
        this.misinformation = misinformation == null ? null : misinformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.OVERNIGHT
     *
     * @return the value of u_list.OVERNIGHT
     *
     * @mbggenerated
     */
    public String getOvernight() {
        return overnight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.OVERNIGHT
     *
     * @param overnight the value for u_list.OVERNIGHT
     *
     * @mbggenerated
     */
    public void setOvernight(String overnight) {
        this.overnight = overnight == null ? null : overnight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TOKEN
     *
     * @return the value of u_list.TOKEN
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TOKEN
     *
     * @param token the value for u_list.TOKEN
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.UPDATESTATUS
     *
     * @return the value of u_list.UPDATESTATUS
     *
     * @mbggenerated
     */
    public Integer getUpdatestatus() {
        return updatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.UPDATESTATUS
     *
     * @param updatestatus the value for u_list.UPDATESTATUS
     *
     * @mbggenerated
     */
    public void setUpdatestatus(Integer updatestatus) {
        this.updatestatus = updatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.jg_time
     *
     * @return the value of u_list.jg_time
     *
     * @mbggenerated
     */
    public Integer getJgTime() {
        return jgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.jg_time
     *
     * @param jgTime the value for u_list.jg_time
     *
     * @mbggenerated
     */
    public void setJgTime(Integer jgTime) {
        this.jgTime = jgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TEMPTASK
     *
     * @return the value of u_list.TEMPTASK
     *
     * @mbggenerated
     */
    public Boolean getTemptask() {
        return temptask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TEMPTASK
     *
     * @param temptask the value for u_list.TEMPTASK
     *
     * @mbggenerated
     */
    public void setTemptask(Boolean temptask) {
        this.temptask = temptask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.TARGETUSERID
     *
     * @return the value of u_list.TARGETUSERID
     *
     * @mbggenerated
     */
    public Integer getTargetuserid() {
        return targetuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.TARGETUSERID
     *
     * @param targetuserid the value for u_list.TARGETUSERID
     *
     * @mbggenerated
     */
    public void setTargetuserid(Integer targetuserid) {
        this.targetuserid = targetuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_list.audit_time
     *
     * @return the value of u_list.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_list.audit_time
     *
     * @param auditTime the value for u_list.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }
}